import Localization from "../../utils/Localization";

const DEFAULT_WIDTH_ICON_COLUMN = 50;
/**
 * @name TableColumnsInfo
 * @description 테이블 컬럼 정보
 */
const TableColumnsInfo = {
  DATACENTERS: [
    { accessor: "icon",          clickable: false,  header: Localization.kr.STATUS, width: DEFAULT_WIDTH_ICON_COLUMN },
    { accessor: '_name',         clickable: true,   header: Localization.kr.NAME, },
    { accessor: 'comment',       clickable: false,  header: Localization.kr.COMMENT,  },
    { accessor: 'storageType',   clickable: false,  header: `${Localization.kr.STORAGE} ${Localization.kr.TYPE}`,  },
    { accessor: 'status',        clickable: false,  header: Localization.kr.STATUS, },
    { accessor: 'hostCnt',       clickable: false,  header: `${Localization.kr.HOST} ${Localization.kr.COUNT}`,     width: '7%' ,align: "center" },
    { accessor: 'clusterCnt',    clickable: false,  header: `${Localization.kr.CLUSTER} ${Localization.kr.COUNT}`,  width: '7%' , align: "center"  },
    { accessor: 'version',       clickable: false,  header: Localization.kr.VERSION_COMPATIBLE,                     width: '7%' , align: "center"  },
    { accessor: 'description',   clickable: false,  header: Localization.kr.DESCRIPTION,  },
  ],
  CLUSTERS_FROM_DATACENTER: [
    { accessor: '_name',         clickable: true,   header: Localization.kr.NAME,               width: 150 },
    { accessor: 'version',       clickable: false,  header: Localization.kr.VERSION_COMPATIBLE, width: 50 },
    { accessor: 'description',   clickable: false,  header: Localization.kr.DESCRIPTION ,       width: 500 },
  ],
  STORAGES_FROM_DATACENTER: [
    { accessor: 'status',        clickable: false,  header: Localization.kr.STATUS, },
    { accessor: 'hostedEngine',  clickable: false,  header: Localization.kr.ENGINE, },
    { accessor: '_name',         clickable: true,   header: `${Localization.kr.DOMAIN} ${Localization.kr.NAME}`, },
    { accessor: 'domainType',    clickable: false,  header: `${Localization.kr.DOMAIN} ${Localization.kr.TYPE}`, },
    { accessor: 'availableSize', clickable: false,  header: `${Localization.kr.SIZE_AVAILABLE} (GiB)`, },
    { accessor: 'usedSize',      clickable: false,  header: `${Localization.kr.SIZE_USED} (GiB)`, },
    { accessor: 'diskSize',      clickable: false,  header: `${Localization.kr.SIZE_TOTAL} (GiB)`, },
    { accessor: 'description',   clickable: false,  header: Localization.kr.DESCRIPTION, },
  ],
  NETWORK_FROM_DATACENTER: [
    { accessor: '_name',         clickable: true,   header: Localization.kr.NAME, width: '14%',},
    { accessor: 'description',   clickable: false,  header: Localization.kr.DESCRIPTION, },
  ],
  CLUSTERS: [
    { accessor: '_name',         clickable: true,   header: Localization.kr.NAME,  width: '13%' },
    { accessor: 'description',   clickable: false,  header: Localization.kr.DESCRIPTION, },
    { accessor: 'cpuType',       clickable: false,  header: `${Localization.kr.CLUSTER} ${Localization.kr.CPU} ${Localization.kr.TYPE}`, },
    { accessor: 'hostCnt',       clickable: false,  header: `${Localization.kr.HOST} ${Localization.kr.COUNT}`, width: '8%' },
    { accessor: 'vmCnt',         clickable: false,  header: `${Localization.kr.VM} ${Localization.kr.COUNT}`, width: '9%'  },
    { accessor: 'comment',       clickable: false,  header: Localization.kr.COMMENT, },
  ],
  NETWORK_FROM_CLUSTER: [
    { accessor: "icon",          clickable: false , header: Localization.kr.STATUS,width: '5%'  },
    { accessor: '_name',         clickable: true,  header: Localization.kr.NAME, width: '18%' },
    { accessor: 'status',        clickable: false, header: Localization.kr.STATUS, width: '15%' },
    { accessor: 'role',          clickable: false, header: Localization.kr.ROLE,  },
    { accessor: 'description',   clickable: false, header: Localization.kr.DESCRIPTION,  },
  ],
  HOSTS: [
    { accessor: "icon",          header: Localization.kr.STATUS,                               clickable: false, width: 30 },
    { accessor: "_hostedEngine", header: Localization.kr.ENGINE,                               clickable: false, width: 30  },
    { accessor: "ha",            header: "HA",                                                 clickable: false, width: 30 },
    { accessor: '_name',         header: Localization.kr.NAME,                                 clickable: true,  },
    { accessor: 'comment',       header: Localization.kr.COMMENT,                              clickable: false},
    { accessor: 'address',       header: `${Localization.kr.HOST} ${Localization.kr.NAME}/IP`, clickable: false },
    { accessor: 'cluster',       header: Localization.kr.CLUSTER,                              clickable: true },
    { accessor: 'dataCenter',    header: Localization.kr.DATA_CENTER,                          clickable: false },
    { accessor: 'vmCnt',         header: `${Localization.kr.VM} ${Localization.kr.COUNT}`,     clickable: false ,align: "center" , width: 80},
    { accessor: 'status',        header: Localization.kr.STATUS,                               clickable: false, width: 50 },
    { accessor: 'memoryUsage',   header: Localization.kr.MEMORY,                               clickable: false, width: 50 },
    { accessor: 'cpuUsage',      header: Localization.kr.CPU,                                  clickable: false, width: 50 },
    { accessor: 'networkUsage',  header: Localization.kr.NETWORK,                              clickable: false, width: 50 },
    { accessor: 'spmStatus',     header: 'SPM',                                                clickable: false, },
    { accessor: 'upTime',        header: Localization.kr.UP_TIME,                              clickable: false, width: 50 },
  ],
  VMS_FROM_HOST: [
    { accessor: "icon",          header: Localization.kr.STATUS,      clickable: false,   width: DEFAULT_WIDTH_ICON_COLUMN },
    { accessor: '_name',         header: Localization.kr.NAME,        clickable: true,    width: '20%' },
    { accessor: 'ipv4',          header: Localization.kr.IP_ADDRESS,  clickable: false,   width: '20%' },
    { accessor: 'fqdn',          header: 'FQDN',                      clickable: false,   width: '20%' },
    { accessor: 'statusKr',      header: Localization.kr.STATUS ,     clickable: false,  },
    { accessor: 'cluster',       header: Localization.kr.CLUSTER ,    clickable: true,   },
    { accessor: 'memoryUsage',   header: Localization.kr.MEMORY ,     clickable: false,  },
    { accessor: 'cpuUsage',      header: Localization.kr.CPU ,        clickable: false,  },
    { accessor: 'networkUsage',  header: Localization.kr.NETWORK ,    clickable: false,  },
    { accessor: 'upTime',        header: Localization.kr.UP_TIME ,    clickable: false,  },
  ],
  NETWORK_INTERFACE_FROM_HOST: [
    { accessor: "icon",          header: "",      width: DEFAULT_WIDTH_ICON_COLUMN },
    { accessor: 'name',          header: Localization.kr.NAME }, // 인터페이스 이름
    { accessor: 'macAddress',    header: 'MAC' }, // MAC 주소
    { accessor: 'rxSpeed',       header: Localization.kr.SPEED_RX }, // Rx 속도
    { accessor: 'txSpeed',       header: Localization.kr.SPEED_TX }, // Tx 속도
    { accessor: 'rxTotalSpeed',  header: Localization.kr.TOTAL_BYTE_RX }, // 총 Rx
    { accessor: 'txTotalSpeed',  header: Localization.kr.TOTAL_BYTE_TX }, // 총 Tx
    { accessor: 'speed',         header: Localization.kr.SPEED }, // 총 Mbps
    { accessor: 'pkts',          header: 'Pkts' } // 패킷 수
  ],
  NETWORK_ADAPTER_FROM_HOST: [
    // { header: "", accessor: "icon" /* width: DEFAULT_WIDTH_ICON_COLUMN */ },
    { accessor: "icon",          header: Localization.kr.STATUS,width: DEFAULT_WIDTH_ICON_COLUMN   },
    { accessor: 'name',          header: Localization.kr.NAME }, // 인터페이스 이름
    { accessor: 'rxSpeed',       header: Localization.kr.SPEED_RX }, // Rx 속도
    { accessor: 'txSpeed',       header: Localization.kr.SPEED_TX }, // Tx 속도
    { accessor: 'autoNegotiation', header: "구성된 속도" }, // autoNegotiation
    { accessor: 'network',       header: '스위치(네트워크?)' }, // 스위치
    { accessor: 'macAddress',    header: 'MAC', }, // MAC 주소
    { accessor: 'ipv4Address',   header: '실제 IP 범위', }, // IP 주소
    // { header: Localization.kr.TOTAL_BYTE_RX, accessor: 'rxTotalSpeed' }, // 총 Rx
    // { header: Localization.kr.TOTAL_BYTE_TX, accessor: 'txTotalSpeed' }, // 총 Tx
    // { header: Localization.kr.SPEED, accessor: 'speed' }, // 총 Mbps
    // { header: 'Pkts', accessor: 'pkts' } // 패킷 수
  ],
  NETWORK_FROM_HOST: [
    // { header: Localization.kr.STATUS, accessor: "icon" /* width: DEFAULT_WIDTH_ICON_COLUMN */ }, // 아이콘
    { accessor: 'bridged',     header: '관리되지 않음', },
    { accessor: 'vlan',        header: 'VLAN', },
    { accessor: 'networkName', header: `${Localization.kr.NETWORK} ${Localization.kr.NAME}`, clickable: true },
    { accessor: 'ipv4',        header: 'IPv4 주소' },
    { accessor: 'ipv6',        header: 'IPv6 주소' }
  ],
  NETWORK_FROM_HOST_SLAVE:[
    { accessor: 'name',                   header: Localization.kr.NAME, clickable: false, },
    { accessor: 'macAddress',             header: 'MAC' }, // MAC 주소
    { accessor: 'speed',                  header: Localization.kr.SPEED, },
    { accessor: 'rxSpeed',                header: Localization.kr.SPEED_RX, },
    { accessor: 'txSpeed',                header: Localization.kr.SPEED_TX, },
    { accessor: 'rxTotalSpeed',           header: Localization.kr.TOTAL_BYTE_RX, },
    { accessor: 'txTotalSpeed',           header: Localization.kr.TOTAL_BYTE_TX, },
    { accessor: 'txTotalError',           header: '중단', },
  ],
  DEVICE_FROM_HOST: [
    { accessor: 'name',          header: Localization.kr.NAME,           clickable: false,               },
    { accessor: 'capability',    header: Localization.kr.CAPABILITIES,   clickable: false,                       },
    { accessor: 'vendorName',    header: Localization.kr.VENDOR,         clickable: false,  },
    { accessor: 'productName',   header: Localization.kr.PRODUCT,        clickable: false,  },
    { accessor: 'driver',        header: '드라이버',                       clickable: false,   },
  ],
  IMPORT_NETWORKS: [
    { accessor: "icon",     clickable: false,   header: Localization.kr.STATUS /* width: DEFAULT_WIDTH_ICON_COLUMN */, },
    { accessor: "nextRun",  clickable: false,   header: Localization.kr.RESET,  width: DEFAULT_WIDTH_ICON_COLUMN, },
    { accessor: "",         clickable: false,   header: Localization.kr.ENGINE /* width: DEFAULT_WIDTH_ICON_COLUMN */, },
    { accessor: '_name',    clickable: true,    header: Localization.kr.NAME,   width: '20%' },
  ],
  VMS: [
    // { header: Localization.kr.RESET, accessor: "nextRun",   clickable: false /* width: DEFAULT_WIDTH_ICON_COLUMN */, },
    { accessor: "icon",          header: Localization.kr.STATUS,      clickable: false , width: DEFAULT_WIDTH_ICON_COLUMN  },
    { accessor: "engine",        header: Localization.kr.ENGINE,      clickable: false , width: DEFAULT_WIDTH_ICON_COLUMN  },
    { accessor: "_name",         header: Localization.kr.NAME,        clickable: true , width: 150 },
    { accessor: 'comment',       header: Localization.kr.COMMENT,     clickable: false, width: 150  },
    { accessor: 'host',          header: Localization.kr.HOST,        clickable: true, width: 130 },
    { accessor: 'ipv4',          header: Localization.kr.IP_ADDRESS,  clickable: false, width: 180 },
    { accessor: 'fqdn',          header: 'FQDN',                      clickable: false },
    { accessor: 'statusKr',      header: Localization.kr.STATUS,      clickable: false },
    { accessor: 'cluster',       header: Localization.kr.CLUSTER,     clickable: true, width: 100 },
    { accessor: 'dataCenter',    header: Localization.kr.DATA_CENTER, clickable: true, width: 100 },
    { accessor: 'memoryUsage',   header: Localization.kr.MEMORY,      clickable: false, width: DEFAULT_WIDTH_ICON_COLUMN},
    { accessor: 'cpuUsage',      header: Localization.kr.CPU,         clickable: false, width: DEFAULT_WIDTH_ICON_COLUMN},
    { accessor: 'networkUsage',  header: Localization.kr.NETWORK,     clickable: false, width: DEFAULT_WIDTH_ICON_COLUMN},
    { accessor: 'upTime',        header: Localization.kr.UP_TIME,     clickable: false, width: DEFAULT_WIDTH_ICON_COLUMN},
    { accessor: 'snapshotExist', header: '스냅샷 여부',                 clickable: false, width: 70 },
    { accessor: 'description',   header: Localization.kr.DESCRIPTION, clickable: false }
  ],
  NICS_FROM_VM: [
    { accessor: 'linked',             header: '연결됨',                 clickable: false, width: '7%' },
    { accessor: 'networkName',        header: `${Localization.kr.NETWORK} ${Localization.kr.NAME}`, clickable: false },
    { accessor: 'vnicProfileName',    header: '프로파일 이름',           clickable: false },
    { accessor: 'status',             header: '링크 상태',              clickable: false },
    { accessor: 'interface_',         header: Localization.kr.TYPE,   clickable: false },
    { accessor: 'speed',              header: Localization.kr.SPEED,  clickable: false },
    { accessor: 'portMirroring',      header: '포트 미러링',            clickable: false },
    { accessor: 'guestInterfaceName', header: '게스트 인터페이스 이름',   clickable: false },
  ],
  NICS2_FROM_VM: [
    { accessor: 'linked',             header: '링크상태',                 clickable: false, width: '7%' },
    { accessor: 'plugged',            header: '연결상태',                 clickable: false, width: '7%' },
    { accessor: 'name',               header: Localization.kr.NAME,                 clickable: false, width: '7%' },
    { accessor: 'network',        header: `${Localization.kr.NETWORK}`, clickable: false },
    { accessor: 'vnicProfile',    header: '프로파일',           clickable: false },
    // { accessor: 'status',             header: '링크 상태',              clickable: false },
    { accessor: 'ipv4',               header: 'IPv4',  clickable: false },
    { accessor: 'ipv6',               header: 'IPv6',  clickable: false },
    { accessor: 'interface_',         header: Localization.kr.TYPE,   clickable: false },
    { accessor: 'speed',              header: Localization.kr.SPEED,  clickable: false },
  ],
  NICS_CALC_FROM_VM: [
    { accessor: 'rxSpeed',          header: Localization.kr.SPEED_RX,       clickable: false, width: '7%' },
    { accessor: 'txSpeed',          header: Localization.kr.SPEED_TX,       clickable: false },
    { accessor: 'rxTotalSpeed',     header: Localization.kr.TOTAL_BYTE_RX,  clickable: false },
    { accessor: 'txTotalSpeed',     header: Localization.kr.TOTAL_BYTE_TX,  clickable: false },
    { accessor: 'pkts',             header: '중단 (Pkts)',                   clickable: false },
  ],
  DISKS_FROM_VM: [
    { accessor: "icon",           header: Localization.kr.STATUS,         clickable: false , width: DEFAULT_WIDTH_ICON_COLUMN  },
    { accessor: '_alias',         header: Localization.kr.ALIAS,          clickable: true },
    { accessor: 'bootable',       header: Localization.kr.IS_BOOTABLE,    clickable: false, width: '4%' },
    { accessor: 'sharable',       header: Localization.kr.IS_SHARABLE,    clickable: false, width: '4%' },
    { accessor: 'readOnly',       header: Localization.kr.IS_READ_ONLY,   clickable: false, width: '4%' },
    { accessor: 'virtualSize',    header: Localization.kr.SIZE_VIRTUAL,   clickable: false, width: '4%'},
    { accessor: 'storageDomain',  header: Localization.kr.DOMAIN,       clickable: false },
    // { accessor: 'connectionvm',   header: `${Localization.kr.CONNECTION} ${Localization.kr.TARGET}`, clickable: false },
    { accessor: 'interface',      header: '인터페이스',                     clickable: false },
    { accessor: 'logicalName',    header: '논리적 이름',                    clickable: false },
    { accessor: 'status',         header: Localization.kr.STATUS,         clickable: false, width: DEFAULT_WIDTH_ICON_COLUMN  },
    { accessor: 'storageType',    header: `${Localization.kr.STORAGE} ${Localization.kr.TYPE}`,                  clickable: false },
    { accessor: 'description',    header: Localization.kr.DESCRIPTION,    clickable: false },
  ],
  DISK_IMAGES_FROM_VM: [
    { accessor: "icon",           header: Localization.kr.STATUS,       clickable: false, width: DEFAULT_WIDTH_ICON_COLUMN  },
    { accessor: '_alias',         header: Localization.kr.ALIAS,        clickable: true },
    { accessor: 'bootable',       header: Localization.kr.IS_BOOTABLE,  clickable: false, width: DEFAULT_WIDTH_ICON_COLUMN  },
    { accessor: 'sharable',       header: Localization.kr.IS_SHARABLE,  clickable: false, width: DEFAULT_WIDTH_ICON_COLUMN  },
    { accessor: 'readOnly',       header: Localization.kr.IS_READ_ONLY, clickable: false, width: DEFAULT_WIDTH_ICON_COLUMN },
    { accessor: 'virtualSize',    header: Localization.kr.SIZE_VIRTUAL, clickable: false },
    { accessor: 'actualSize',     header: Localization.kr.SIZE_ACTUAL,  clickable: false },
    { accessor: 'sparse',         header: Localization.kr.SPARSE,       clickable: false },
    { accessor: 'storageDomain',  header: Localization.kr.DOMAIN,       clickable: false },
    { accessor: 'storageType',    header: `${Localization.kr.STORAGE} ${Localization.kr.TYPE}`,                clickable: false },
    { accessor: 'creationDate',   header: Localization.kr.DATE_CREATED, clickable: false },
    { accessor: 'connectionvm',   header: `${Localization.kr.CONNECTION} ${Localization.kr.TARGET}`, clickable: false },
    { accessor: 'interface',      header: '인터페이스',                   clickable: false },
    { accessor: 'logicalName',    header: '논리적 이름',                  clickable: false },
    { accessor: 'status',         header: Localization.kr.STATUS,       clickable: false },
    { accessor: 'description',    header: Localization.kr.DESCRIPTION,  clickable: false },
  ],
  DISK_LUN_FROM_VM: [
    { accessor: 'status',         header: '',                           clickable: false, width: '4%' },
    { accessor: '_alias',         header: Localization.kr.ALIAS,        clickable: true, width: '10%' },
    { accessor: 'bootable',       header: Localization.kr.IS_BOOTABLE,  clickable: false, width: '4%' },
    { accessor: 'sharable',       header: Localization.kr.IS_SHARABLE,  clickable: false, width: '4%' },
    { accessor: 'readOnly',       header: Localization.kr.IS_READ_ONLY, clickable: false, width: '4%' },
    { accessor: 'virtualSize',    header: Localization.kr.SIZE_VIRTUAL, clickable: false },
    { accessor: 'lunId',          header: 'LUN ID',                     clickable: false },
    { accessor: 'serial',         header: '시리얼',                      clickable: false },
    { accessor: 'venderId',       header: `${Localization.kr.VENDOR} ID`,                     clickable: false },
    { accessor: 'productId',      header: `${Localization.kr.PRODUCT} ID`,                     clickable: false },
    { accessor: 'connectionvm',   header: `${Localization.kr.CONNECTION} ${Localization.kr.TARGET}`, clickable: false },
    { accessor: 'interface',      header: '인터페이스',                   clickable: false },
    { accessor: 'logicalName',    header: '논리적 이름',                  clickable: false },
    { accessor: 'description',    header: Localization.kr.DESCRIPTION,  clickable: false },
  ],
  APPLICATIONS_FROM_VM: [
    { accessor: 'name', header: '설치된 애플리케이션' }
  ],
  HOST_DEVICE_FROM_VM: [
    { accessor: 'name',         header: Localization.kr.NAME,          clickable: false },
    { accessor: 'capability',   header: Localization.kr.CAPABILITIES,  clickable: false },
    { accessor: 'vendorName',   header: Localization.kr.VENDOR,        clickable: false },
    { accessor: 'productName',  header: Localization.kr.PRODUCT,       clickable: false },
    { accessor: 'driver',       header: '드라이버',                clickable: false },
    { accessor: 'used',         header: '현재 사용중',             clickable: false },
  ],
  SNAPSHOT_INFO_FROM_VM: [
    { accessor: 'description',    header: Localization.kr.NAME,   clickable: false },
    { accessor: 'date',           header: Localization.kr.DATE,   clickable: false, width: '5%' },
    { accessor: 'statusKr',       header: Localization.kr.STATUS, clickable: false, width: '5%' },
    { accessor: 'persistMemory',  header: '메모리 여부',            clickable: false },
    { accessor: 'memorySize',     header: '설정된 메모리',          clickable: false },
    { accessor: 'memoryActual',   header: '할당할 실제 메모리',      clickable: false },
  ],
  SNAPSHOT_DISK_FROM_VM: [
    { accessor: 'status',           header: Localization.kr.STATUS,       clickable: false, width: '5%' },
    { accessor: 'alias',            header: Localization.kr.ALIAS,        clickable: false, width: '17%' },
    { accessor: 'date',             header: Localization.kr.DATE_CREATED, clickable: false },
    { accessor: 'provisionedSize',  header: Localization.kr.SIZE_VIRTUAL, clickable: false },
    { accessor: 'actualSize',       header: Localization.kr.SIZE_ACTUAL,  clickable: false },
    { accessor: 'sparse',           header: Localization.kr.SPARSE,       clickable: false },
    { accessor: 'interface_',       header: '인터페이스',                   clickable: false },
    { accessor: 'description',      header: Localization.kr.DESCRIPTION,  clickable: false },
    { accessor: 'imageId',          header: '디스크 스냅샷 ID',             clickable: false, width: '16%' },
  ],
  SNAPSHOT_NIC_FROM_VM: [
    { accessor: 'name',           header: Localization.kr.NAME,    clickable: false, width: '10%' },
    { accessor: 'networkName',    header: `${Localization.kr.NETWORK} ${Localization.kr.NAME}`, clickable: false, width: '15%' },
    { accessor: 'profileName',    header: '프로파일 이름',           clickable: false, width: '15%' },
    { accessor: 'interface_',     header: '유형',                   clickable: false, width: '10%' },
    { accessor: 'macAddress',     header: 'MAC',                   clickable: false, width: '15%' },
    { accessor: 'rxSpeed',        header: 'Rx 속도 (Mbps)',         clickable: false, width: '10%' },
    { accessor: 'txSpeed',        header: 'Tx 속도 (Mbps)',         clickable: false, width: '10%' },
    { accessor: 'txTotalError',   header: '중단 (Pkts)',            clickable: false, width: '10%' },
  ],
  SNAPSHOT_APPLICATION_FROM_VM: [
    { accessor: 'name',         header: '애플리케이션 이름',            clickable: false, width: '10%' },
    { accessor: 'version',      header: '버전',                       clickable: false, width: '15%' },
    { accessor: 'description',  header: Localization.kr.DESCRIPTION, clickable: false, width: '15%' },
  ],
  TEMPLATES: [
    { accessor: '_name',        header: Localization.kr.NAME,         clickable: true},
    { accessor: 'creationTime', header: Localization.kr.DATE_CREATED, clickable: false },
    { accessor: 'status',       header: Localization.kr.STATUS,       clickable: false, width: DEFAULT_WIDTH_ICON_COLUMN  },
    { accessor: 'version',      header: '버전',                        clickable: false },
    { accessor: 'comment',      header: Localization.kr.COMMENT,      clickable: false },
    { accessor: 'status',       header: '보관',                        clickable: false, width: DEFAULT_WIDTH_ICON_COLUMN  },
    { accessor: 'cluster',      header: Localization.kr.CLUSTER,      clickable: true },
    { accessor: 'dataCenter',   header: Localization.kr.DATA_CENTER,  clickable: true },
    { accessor: 'description',  header: Localization.kr.DESCRIPTION,  clickable: false },
  ],
  VMS_FROM_TEMPLATE: [
    { accessor: "icon",     header: Localization.kr.STATUS,     clickable: false, width: '5%' },
    { accessor: '_name',    header: Localization.kr.NAME,       clickable: true, width: '10%' },
    { accessor: 'ipv4',     header: Localization.kr.IP_ADDRESS, clickable: false, width: '10%' },
    { accessor: 'fqdn',     header: 'FQDN',                     clickable: false, width: '10%' },
    { accessor: 'status',   header: Localization.kr.STATUS,     clickable: false, width: '10%' },
    { accessor: 'host',     header: Localization.kr.HOST,       clickable: true, width: '15%' },
    { accessor: 'upTime',   header: Localization.kr.UP_TIME,    clickable: false, width: '20%' },
  ],
  NICS_FROM_TEMPLATE: [
    { accessor: 'status',       header: '',             clickable: false, width: DEFAULT_WIDTH_ICON_COLUMN  },
    { accessor: 'name',         header: Localization.kr.NAME, clickable: false },
    { accessor: '_plugged',     header: '연결됨',        clickable: true },
    { accessor: 'network',      header: `${Localization.kr.NETWORK} ${Localization.kr.NAME}`, clickable: false },
    { accessor: 'vnicProfile',  header: '프로파일 이름',  clickable: false },
    { accessor: '_linked',      header: '링크 상태',     clickable: false },
    { accessor: 'interface_',   header: '유형',         clickable: false },
  ],
  DISKS_FROM_TEMPLATE: [
    { accessor: '_alias',             header: Localization.kr.ALIAS,        clickable: false, width: 120 },
    { accessor: 'name',               header: 'R/O',                        clickable: false },
    { accessor: 'virtualSize',        header: Localization.kr.SIZE_VIRTUAL, clickable: true },
    { accessor: 'actualSize',         header: Localization.kr.SIZE_ACTUAL,  clickable: false },
    { accessor: 'status',             header: Localization.kr.STATUS,       clickable: false, width: DEFAULT_WIDTH_ICON_COLUMN },
    { accessor: 'storageDomainName',  header: Localization.kr.DOMAIN,       clickable: false },
    { accessor: 'policy',             header: Localization.kr.SPARSE,       clickable: false },
    { accessor: 'interfaceType',      header: '인터페이스',                   clickable: false },
    { accessor: 'storageType',        header: '유형',                        clickable: false },
    // { accessor: 'creationTime', header: Localization.kr.DATE_CREATED, clickable: false },
  ],

  NETWORKS: [
    { accessor: '_name',         header: Localization.kr.NAME,        clickable: true },
    { accessor: 'comment',       header: Localization.kr.COMMENT,     clickable: false },
    { accessor: 'datacenter',    header: Localization.kr.DATA_CENTER, clickable: false },
    { accessor: 'description',   header: Localization.kr.DESCRIPTION, clickable: false },
    { accessor: 'vlan',          header: 'VLAN 태그',                 clickable: false },
    // { accessor: 'label',      header: '레이블',                     clickable: false },
    { accessor: 'mtu',           header: 'MTU',                       clickable: false }
    ],
  VNIC_PROFILES_FROM_NETWORK: [
    { accessor: '_name',          header: Localization.kr.NAME,           clickable: false },
    { accessor: 'network',        header: Localization.kr.NETWORK,        clickable: false },
    { accessor: 'dataCenter',     header: Localization.kr.DATA_CENTER,    clickable: true },
    { accessor: 'networkFilter',  header: Localization.kr.NETWORK_FILTER, clickable: false },
    { accessor: 'portMirroring',  header: '포트 미러링',                    clickable: false, align: "left" },
    { accessor: 'passThrough',    header: '통과',                          clickable: false },
    { accessor: 'description',    header: Localization.kr.DESCRIPTION,    clickable: false },
  ],
  CLUSTERS_FRON_NETWORK: [
    { accessor: 'status',      header: '네트워크 상태',               clickable: false, width: '7%' },
    { accessor: '_name',       header: Localization.kr.NAME,        clickable: true, width: '15%' },
    { accessor: 'connect',     header: '연결된 네트워크',             clickable: false, width: '9%' },
    { accessor: 'required',    header: '필수 네트워크',               clickable: false, width: '9%' },
    { accessor: 'networkRole', header: '네트워크 역할',               clickable: false },
    // { accessor: 'description', header: Localization.kr.DESCRIPTION, clickable: false },
  ],
  HOSTS_FROM_NETWORK: [
    { accessor: "icon",                 header: Localization.kr.STATUS,         clickable: false , width: DEFAULT_WIDTH_ICON_COLUMN },
    { accessor: 'host',                 header: Localization.kr.NAME,           clickable: false, width: '10%' },
    { accessor: 'cluster',              header: Localization.kr.CLUSTER,        clickable: true, width: '10%' },
    { accessor: 'dataCenter',           header: Localization.kr.DATA_CENTER,    clickable: true },
    { accessor: 'networkDeviceStatus',  header: '네트워크 장치 상태',              clickable: false, width: '10%' },
    { accessor: 'async',                header: '비동기',                        clickable: false },
    { accessor: 'networkDevice',        header: '네트워크 장치',                  clickable: false },
    { accessor: 'speed',                header: Localization.kr.SPEED,          clickable: false },
    { accessor: 'rx',                   header: Localization.kr.SPEED_RX,       clickable: false, width: '7%' },
    { accessor: 'tx',                   header: Localization.kr.SPEED_TX,       clickable: false, width: '7%' },
    { accessor: 'totalRx',              header: Localization.kr.TOTAL_BYTE_RX,  clickable: false },
    { accessor: 'totalTx',              header: Localization.kr.TOTAL_BYTE_TX,  clickable: false },
  ],
  HOSTS_DISCONNECT_FROM_NETWORK: [
    { accessor: "icon",       header: Localization.kr.STATUS,       clickable: false , width: 5 },
    { accessor: 'name',       header: Localization.kr.NAME,         clickable: false },
    { accessor: 'cluster',    header: Localization.kr.CLUSTER,      clickable: false },
    { accessor: 'dataCenter', header: Localization.kr.DATA_CENTER,  clickable: false },
  ],
  VMS_FROM_NETWORK: [
    { accessor: "icon",         header: Localization.kr.STATUS,         clickable: false , width: DEFAULT_WIDTH_ICON_COLUMN  },
    { accessor: 'name',         header: Localization.kr.NAME,           clickable: false },
    { accessor: 'cluster',      header: Localization.kr.CLUSTER,        clickable: false },
    { accessor: 'ipAddress',    header: Localization.kr.IP_ADDRESS,     clickable: false },
    { accessor: 'fqdn',         header: 'FQDN',                         clickable: false },
    { accessor: 'icon',         header: `${Localization.kr.VNIC} ${Localization.kr.STATUS}`, clickable: false },
    { accessor: 'vnic',         header: Localization.kr.VNIC,           clickable: false },
    { accessor: 'vnicRx',       header: 'vNIC Rx',                      clickable: false },
    { accessor: 'vnicTx',       header: 'vNIC Tx',                      clickable: false },
    { accessor: 'totalRx',      header: Localization.kr.TOTAL_BYTE_RX,  clickable: false },
    { accessor: 'totalTx',      header: Localization.kr.TOTAL_BYTE_TX,  clickable: false },
    { accessor: 'description',  header: Localization.kr.DESCRIPTION,    clickable: false }
  ],
  VMS_UP_FROM_NETWORK: [
    { accessor: "icon",         header: Localization.kr.STATUS,        clickable: false , width: DEFAULT_WIDTH_ICON_COLUMN  },
    { accessor: '_name',        header: Localization.kr.NAME,          clickable: false },
    // { accessor: 'cluster',   header: Localization.kr.CLUSTER, clickable: false },
    { accessor: 'ipAddress',    header: Localization.kr.IP_ADDRESS,    clickable: false },
    { accessor: 'fqdn',         header: 'FQDN',                        clickable: false },
    { accessor: 'vnicStatus',   header: `${Localization.kr.VNIC} ${Localization.kr.STATUS}`, clickable: false, width: '7%' },
    { accessor: 'vnic',         header: Localization.kr.VNIC,          clickable: false },
    { accessor: 'vnicRx',       header: 'vNIC Rx',                     clickable: false },
    { accessor: 'vnicTx',       header: 'vNIC Tx',                     clickable: false },
    { accessor: 'totalRx',      header: Localization.kr.TOTAL_BYTE_RX, clickable: false },
    { accessor: 'totalTx',      header: Localization.kr.TOTAL_BYTE_TX, clickable: false },
    { accessor: 'description',  header: Localization.kr.DESCRIPTION,   clickable: false }
  ],
  VMS_STOP_FROM_NETWORK: [
    { accessor: "icon",         header: Localization.kr.STATUS,      clickable: false /* width: DEFAULT_WIDTH_ICON_COLUMN */ },
    { accessor: '_name',        header: Localization.kr.NAME,        clickable: false },
    // { accessor: 'cluster', header: Localization.kr.CLUSTER, clickable: false },
    { accessor: 'ipAddress',    header: Localization.kr.IP_ADDRESS,  clickable: false },
    { accessor: 'fqdn',         header: 'FQDN',                      clickable: false },
    { accessor: 'vnicStatus',   header: `${Localization.kr.VNIC} ${Localization.kr.STATUS}`, clickable: false, width: '7%' },
    { accessor: 'vnic',         header: Localization.kr.VNIC,        clickable: false },
    { accessor: 'description',  header: Localization.kr.DESCRIPTION, clickable: false }
  ],
  TEMPLATES_FROM_NETWORK: [
    { accessor: 'name',         header: Localization.kr.NAME,     clickable: false },
    // { accessor: 'ver',          header: '버전',                   clickable: false },
    { accessor: 'status',       header: Localization.kr.STATUS,   clickable: false },
    { accessor: 'clusterName',  header: Localization.kr.CLUSTER,  clickable: false },
    { accessor: 'nicName',      header: Localization.kr.VNIC,     clickable: false },
  ],

  VNIC_PROFILES: [
    { accessor: '_name',        header: Localization.kr.NAME,           clickable: false },
    { accessor: 'network',      header: Localization.kr.NETWORK,        clickable: true },
    { accessor: 'dataCenter',   header: Localization.kr.DATA_CENTER,    clickable: true },
    { accessor: 'networkFilter',header: Localization.kr.NETWORK_FILTER, clickable: false },
    { accessor: 'portMirroring',header: '포트 미러링',                    clickable: false, align: "left" },
    { accessor: 'passThrough',  header: '통과',                          clickable: false },
    { accessor: 'description',  header: Localization.kr.DESCRIPTION,    clickable: false },
  ],
  VMS_FROM_VNIC_PROFILE: [
    { accessor: 'name', header: Localization.kr.NAME, clickable: false },
  ],
  TEMPLATE_FROM_VNIC_PROFILE: [
    { accessor: '_name',      header: Localization.kr.NAME, clickable: false },
    // { accessor: 'versionNum', header: '버전',                clickable: false },
  ],

  STORAGE_DOMAINS: [
    { accessor: "icon",           header: Localization.kr.STATUS,         width: DEFAULT_WIDTH_ICON_COLUMN },
    { accessor: 'hostedEngine',   header: Localization.kr.ENGINE,          width: DEFAULT_WIDTH_ICON_COLUMN },
    { accessor: '_name',          header: '도메인 이름',                     width: 150  },
    { accessor: 'storageDomainType',     header: '도메인 유형' },
    { accessor: 'storageType',    header: `${Localization.kr.STORAGE} ${Localization.kr.TYPE}`,                    width: 150  },
    { accessor: 'format',         header: '포맷' },
    { accessor: '_status',        header: '데이터 센터간 상태',                width: 150   },
    { accessor: 'availableSize',  header: Localization.kr.SIZE_AVAILABLE,   width: 70 },
    { accessor: 'usedSize',       header: Localization.kr.SIZE_USED,        width: 70     },
    { accessor: 'size',           header: Localization.kr.SIZE_TOTAL,       width: 70     },
    { accessor: 'description',    header: Localization.kr.DESCRIPTION                     },
    { accessor: 'comment',        header: Localization.kr.COMMENT,          width: 170    },
  ],
  DATACENTERS_FROM_STORAGE_DOMAIN: [
    { accessor: "icon",           header: Localization.kr.STATUS,     clickable: false, width: 30 },
    { accessor: '_name',          header: Localization.kr.NAME,       clickable: false, width: 100 },
    { accessor: '_domainStatus',  header: `${Localization.kr.DATA_CENTER} 내의 도메인 상태`, clickable: false , width: 640 },
  ],
  DATACENTERS_ATTACH_FROM_STORAGE_DOMAIN: [
    { accessor: 'name',           header: Localization.kr.NAME, clickable: false, width: '20%' },
    { accessor: 'domainType',     header: '유형',                clickable: false, width: '17%' },
    { accessor: 'storageType',    header: '타입',                clickable: false, width: '17%' },
    { accessor: 'availableSize',  header: '여유 공간',            clickable: false, width: '17%' },
  ],
  STORAGE_DOMAINS_ATTACH_FROM_DATACENTER: [
    { accessor: 'name',           header: Localization.kr.NAME, clickable: false, width: '20%' },
    { accessor: 'storageType',    header: '유형',                clickable: false, width: '17%' },
  ],
  TEMPLATES_FROM_STORAGE_DOMAIN: [
    { accessor: '_name',        header: Localization.kr.ALIAS,        clickable: false },
    { accessor: 'disk',         header: '디스크',                      clickable: false },
    { accessor: 'virtualSize',  header: Localization.kr.SIZE_VIRTUAL, clickable: false },
    { accessor: 'actualSize',   header: Localization.kr.SIZE_ACTUAL,  clickable: false },
    { accessor: 'creationTime', header: Localization.kr.DATE_CREATED, clickable: false },
  ],
  VMS_FROM_STORAGE_DOMAIN: [
    { accessor: '_name',          header: Localization.kr.ALIAS,        clickable: false },
    { accessor: 'disk',           header: '디스크',                      clickable: false },
    { accessor: 'snapshot',       header: '스냅샷',                      clickable: false },
    { accessor: 'virtualSize',    header: Localization.kr.SIZE_VIRTUAL, clickable: false },
    { accessor: 'actualSize',     header: Localization.kr.SIZE_ACTUAL,  clickable: false },
    { accessor: 'creationTime',   header: Localization.kr.DATE_CREATED, clickable: false },
  ],
  TARGETS_LUNS: [
    { accessor: 'target',   header: 'Target Name',  clickable: true },
    { accessor: 'address',  header: 'address',      clickable: true },
    { accessor: 'port',     header: 'port',         clickable: true },
  ],
  LUNS_TARGETS: [
    { accessor: 'abled',      header: '여부',         clickable: false },
    { accessor: 'status',     header: 'status',       clickable: false },
    { accessor: 'lunId',      header: 'Lun ID',       clickable: false },
    { accessor: 'size',       header: Localization.kr.SIZE_ACTUAL, clickable: false },
    { accessor: 'paths',      header: '#path',        clickable: false },
    { accessor: 'vendorId',   header: 'vendor ID',    clickable: false },
    { accessor: 'productId',  header: 'product ID',   clickable: false },
    { accessor: 'serial',     header: 'serial',       clickable: false },
    { accessor: 'target',     header: 'Target Name',  clickable: true },
    { accessor: 'address',    header: 'address',      clickable: true },
    { accessor: 'port',       header: 'port',         clickable: true },
  ],
  IMPORT_ISCSI: [
    { accessor: 'target',   header: 'IQN',      clickable: true },
    { accessor: 'address',  header: 'address',  clickable: true },
    { accessor: 'port',     header: 'port',     clickable: true },
  ],
  FIBRE: [
    { accessor: 'able',             header: 'able',             clickable: false },
    { accessor: 'check',            header: 'check',            clickable: false },
    { accessor: 'status',           header: 'status',           clickable: false },
    { accessor: 'id',               header: 'Lun ID',           clickable: false },
    { accessor: 'size',             header: 'size',             clickable: false },
    { accessor: 'paths',            header: '#path',            clickable: false },
    { accessor: 'vendorId',         header: 'vendor ID',        clickable: false },
    // { accessor: 'productId', header: 'product ID', clickable: false },
    { accessor: 'serial',           header: 'serial',           clickable: false },
    { accessor: 'storageDomainId',  header: 'storageDomainId',  clickable: false },
  ],
  UPDATE_FIBRE: [
    { accessor: 'able',       header: 'able',       clickable: false, width: 60 },
    { accessor: 'id',         header: 'Lun ID',     clickable: false },
    { accessor: 'size',       header: 'size',       clickable: false },
    { accessor: 'paths',      header: '#path',      clickable: false },
    { accessor: 'vendorId',   header: 'vendor ID',  clickable: false },
    { accessor: 'serial',     header: 'serial',     clickable: false },
  ],
  IMPORT_FIBRE: [
    { accessor: 'able', header: 'able',               clickable: false },
    { accessor: 'name', header: Localization.kr.NAME, clickable: true, width: '30%' },
    { accessor: 'id',   header: '스토리지 Id',          clickable: true },
  ],
  DISKS_FROM_STORAGE_DOMAIN: [
    { accessor: '_alias',       header: Localization.kr.ALIAS,        clickable: false },
    { accessor: 'icon1',        header: Localization.kr.IS_BOOTABLE,  clickable: false },
    { accessor: 'sharable',     header: Localization.kr.IS_SHARABLE,  clickable: false },
    { accessor: 'virtualSize',  header: Localization.kr.SIZE_VIRTUAL, clickable: false },
    { accessor: 'actualSize',   header: Localization.kr.SIZE_ACTUAL,  clickable: false },
    { accessor: 'sparse',       header: Localization.kr.SPARSE,       clickable: false },
    // { accessor: 'storageDomain', header: Localization.kr.DOMAIN, clickable: false },
    // { accessor: 'creationDate', header: Localization.kr.DATE_CREATED, clickable: false },
    { accessor: 'connect',      header: `${Localization.kr.CONNECTION} ${Localization.kr.TARGET}`, clickable: false },
    // { accessor: 'connectTemplate', header: `${Localization.kr.CONNECTION} ${Localization.kr.TARGET}(템플릿)`, clickable: false },
    { accessor: 'status',       header: Localization.kr.STATUS,       clickable: false },
    { accessor: 'storageType',  header: '유형',                        clickable: false },
    { accessor: 'description',  header: Localization.kr.DESCRIPTION,  clickable: false },
    { accessor: 'dateCreated',  header: Localization.kr.DATE_CREATED,  clickable: false },
  ],
  DISK_SNAPSHOT_FROM_STORAGE_DOMAIN: [
    { accessor: 'actualSize',              header: Localization.kr.SIZE_ACTUAL,                clickable: false },
    { accessor: 'creationDate',            header: Localization.kr.DATE_CREATED,               clickable: false },
    { accessor: 'vmSnapshotCreationDate',  header: `${Localization.kr.SNAPSHOT} 생성일`,        clickable: false },
    { accessor: 'alias',                   header: '디스크 별칭',                               clickable: false },
    { accessor: 'vmSnapshotDescription',   header: `${Localization.kr.SNAPSHOT} ${Localization.kr.DESCRIPTION}`, clickable: false },
    { accessor: 'vmNameConnected',         header: `${Localization.kr.CONNECTION} ${Localization.kr.TARGET}`, clickable: false },
    { accessor: 'status',                  header: Localization.kr.STATUS,                     clickable: false },
    { accessor: 'id',                      header: `${Localization.kr.DISK} ${Localization.kr.SNAPSHOT} ID`, clickable: false },
  ],
  GET_VMS_TEMPLATES: [
    { accessor: 'name',          header: Localization.kr.NAME,         clickable: false, width: '10%' },
    { accessor: 'memory',        header: Localization.kr.MEMORY,       clickable: false },
    { accessor: 'cpu',           header: Localization.kr.CPU,          clickable: false },
    { accessor: 'cpuArc',        header: Localization.kr.ARCH,         clickable: false },
    { accessor: 'disk',          header: Localization.kr.DISK,         clickable: false },
    { accessor: 'creationTime',  header: Localization.kr.DATE_CREATED, clickable: false },
  ],
  TEMPLATES_IMPORT_NAMES: [
    { accessor: 'name',    header: Localization.kr.NAME,     clickable: false, width: '10%' },
    { accessor: 'memory',  header: Localization.kr.MEMORY,   clickable: false },
    { accessor: 'cpu',     header: Localization.kr.CPU,      clickable: false },
    { accessor: 'cpuArc',  header: Localization.kr.ARCH,     clickable: false },
    { accessor: 'disk',    header: Localization.kr.DISK,     clickable: false },
    { accessor: '',        header: Localization.kr.CLUSTER,  clickable: false },
  ],
  VMS_IMPORT_NAMES: [
    { accessor: 'name',     header: Localization.kr.NAME,        clickable: false, width: '10%' },
    { accessor: 'memory',   header: Localization.kr.MEMORY,      clickable: false },
    { accessor: 'cpu',      header: Localization.kr.CPU,         clickable: false },
    { accessor: 'cpuArc',   header: Localization.kr.ARCH,        clickable: false },
    { accessor: 'diskCnt',  header: `${Localization.kr.DISK} ${Localization.kr.COUNT}`, clickable: false },
    { accessor: 'mac',      header: '불량 MAC 재배치',             clickable: false },
    { accessor: 'allow',    header: '부분 허용',                  clickable: false },
    { accessor: 'cluster',  header: Localization.kr.CLUSTER,     clickable: false },
  ],
  VMS_DISKS_IMPORT_FROM_STORAGE_DOMAIN: [
    { accessor: '_alias',       header: Localization.kr.ALIAS,          clickable: true },
    { accessor: 'virtualSize',  header: Localization.kr.SIZE_VIRTUAL,   clickable: false },
    { accessor: 'actualSize',   header: Localization.kr.SIZE_ACTUAL,    clickable: false },
    { accessor: 'storageType',  header: `${Localization.kr.STORAGE} ${Localization.kr.TYPE}`,                clickable: false },
    { accessor: 'sparse',       header: Localization.kr.SPARSE,         clickable: false },
    { accessor: 'description',  header: Localization.kr.DESCRIPTION,    clickable: false },
  ],
  VMS_VNICPROFILES_IMPORT_FROM_STORAGE_DOMAIN: [
    { accessor: 'network',          header: `외부 논리적 ${Localization.kr.NETWORK}`,  clickable: true },
    { accessor: 'externalVnicProfile', header: `외부 ${Localization.kr.VNIC_PROFILE}`, clickable: false },
    { accessor: 'vnicProfile',      header: `대상 ${Localization.kr.VNIC_PROFILE}`,    clickable: false },
  ],
  VMS_IMPORT_FROM_STORAGE_DOMAIN: [
    { accessor: 'name',           header: Localization.kr.NAME,         clickable: false, width: '10%' },
    { accessor: 'memory',         header: Localization.kr.MEMORY,       clickable: false },
    { accessor: 'cpuTopologyCnt', header: Localization.kr.CPU,          clickable: false },
    { accessor: 'cpuArc',         header: Localization.kr.ARCH,         clickable: false },
    { accessor: 'diskCnt',        header: `${Localization.kr.DISK} ${Localization.kr.COUNT}`,  clickable: false },
    { accessor: 'creationTime',   header: Localization.kr.DATE_CREATED, clickable: false },
    // { accessor: 'stopTime',     header: '중지 일자',                   clickable: false },
  ], 
  
GET_IMPORT_VMS: [
  { accessor: "clone",    header: "복제", clickable: false },
  { accessor: "name",     header: "이름", clickable: false },
  { accessor: "source",   header: "소스", clickable: false },
  { accessor: "memory",   header: "메모리", clickable: false },
  { accessor: "cpu",      header: "CPU", clickable: false },
  { accessor: "arch",     header: "아키텍처", clickable: false },
  { accessor: "disk",     header: "디스크", clickable: false }
],
  GET_DISK_TEMPLATES: [
    { accessor: 'alias',          header: Localization.kr.ALIAS,        clickable: true, width: '10%' },
    { accessor: 'virtualSize',    header: Localization.kr.SIZE_VIRTUAL, clickable: false },
    { accessor: 'creationTime',   header: Localization.kr.DATE_CREATED, clickable: false },
    { accessor: 'sparse',         header: Localization.kr.SPARSE,       clickable: false },
    { accessor: 'status',         header: Localization.kr.STATUS,       clickable: false },
    { accessor: 'storageType',    header: `${Localization.kr.STORAGE} ${Localization.kr.TYPE}`,              clickable: false },
    { accessor: 'date',           header: Localization.kr.DATE_CREATED, clickable: false },
    { accessor: 'description',    header: Localization.kr.DESCRIPTION,  clickable: false },
  ],
  GET_DISKS: [
    { accessor: 'alias',         header: Localization.kr.ALIAS,         clickable: false },
    { accessor: 'actualSize',    header: Localization.kr.SIZE_ACTUAL,   clickable: false },
    { accessor: 'virtualSize',   header: Localization.kr.SIZE_VIRTUAL,  clickable: false },
    { accessor: 'sparse',        header: Localization.kr.SPARSE,        clickable: false },
    { accessor: 'dateCreated',   header: Localization.kr.DATE_CREATED,  clickable: false },
    { accessor: 'description',   header: Localization.kr.DESCRIPTION,   clickable: false },
  ],
  DISKS_IMPORT_FROM_STORAGE_DOMAIN: [
    { accessor: 'alias',        header: Localization.kr.ALIAS,         clickable: false },
    { accessor: 'virtualSize',  header: Localization.kr.SIZE_VIRTUAL,  clickable: false },
    { accessor: 'diskProfile',  header: Localization.kr.DISK_PROFILE,  clickable: false },
  ],
  TEMPLATE_VMS: [
    { accessor: "icon",        header: Localization.kr.STATUS,       clickable: false /* width: DEFAULT_WIDTH_ICON_COLUMN */ },
    { accessor: 'name',        header: Localization.kr.NAME,         clickable: true,  width: '20%' },
    { accessor: 'hostVo',      header: Localization.kr.HOST,         clickable: true,  width: '25%' },
    { accessor: 'ipv4',        header: Localization.kr.IP_ADDRESS,   clickable: false, width: '20%' },
    { accessor: 'fqdn',        header: 'FQDN',                       clickable: false, width: '20%' },
    { accessor: 'status',      header: Localization.kr.STATUS,       clickable: false, width: '10%' },
    { accessor: 'upTime',      header: Localization.kr.UP_TIME,      clickable: false, width: '20%' },
    { accessor: 'description', header: Localization.kr.DESCRIPTION,  clickable: false, width: '25%' },
  ],
  DISKS: [
    { accessor: '_alias',       header: Localization.kr.ALIAS,         clickable: true },
    { accessor: 'id',           header: 'ID',                          clickable: false },
    // { accessor: 'icon1',      header: Localization.kr.IS_SHARABLE,   clickable: false },
    // { accessor: 'type',         header: '연결',                            clickable: false },
    { accessor: 'connect',      header: `${Localization.kr.CONNECTION} ${Localization.kr.TARGET}`, clickable: false, align: "left" },
    { accessor: 'storageDomain',header: Localization.kr.DOMAIN,        clickable: false },
    { accessor: 'virtualSize',  header: Localization.kr.SIZE_VIRTUAL,  clickable: false , width: DEFAULT_WIDTH_ICON_COLUMN},
    { accessor: 'status',       header: Localization.kr.STATUS,        clickable: false , width: DEFAULT_WIDTH_ICON_COLUMN},
    { accessor: 'storageType',  header: '유형',                        clickable: false, width: DEFAULT_WIDTH_ICON_COLUMN },
    { accessor: 'description',  header: Localization.kr.DESCRIPTION,   clickable: false },
    { accessor: 'dateCreated',  header: Localization.kr.DATE_CREATED,  clickable: false },
  ],
  VMS_FROM_DISK: [
    { accessor: "icon",         header: Localization.kr.STATUS,       clickable: false ,width: DEFAULT_WIDTH_ICON_COLUMN},
    { accessor: 'name',         header: Localization.kr.NAME,         clickable: false },
    { accessor: 'cluster',      header: Localization.kr.CLUSTER,      clickable: false },
    { accessor: 'ipAddress',    header: Localization.kr.IP_ADDRESS,   clickable: false },
    { accessor: 'uptime',       header: Localization.kr.UP_TIME,      clickable: false },
  ],
  STORAGE_DOMAINS_FROM_DISK: [
    { accessor: "icon",         header: Localization.kr.STATUS,       clickable: false,width: DEFAULT_WIDTH_ICON_COLUMN },
    { accessor: 'storageDomain',header: '도메인 이름',                clickable: false },
    { accessor: 'domainType',   header: '도메인 유형',                clickable: false },
    { accessor: 'status',       header: Localization.kr.STATUS,       clickable: false },
    // { accessor: 'diskSize',   header: Localization.kr.SIZE_TOTAL,   clickable: false },
    { accessor: 'availableSize',header: Localization.kr.SIZE_AVAILABLE, clickable: false },
    { accessor: 'usedSize',     header: Localization.kr.SIZE_USED,    clickable: false },
    { accessor: 'description',  header: Localization.kr.DESCRIPTION,  clickable: false },
  ],
  VIRTUAL_DISK: [
    { accessor: 'check',        header: "선택",                        clickable: false, width: '6%' },
    { accessor: 'alias',        header: Localization.kr.ALIAS,         clickable: true },
    { accessor: 'description',  header: Localization.kr.DESCRIPTION,   clickable: false },
    { accessor: 'id',           header: 'ID',                          clickable: false },
    { accessor: 'virtualSize',  header: Localization.kr.SIZE_VIRTUAL,  clickable: false },
    { accessor: 'actualSize',   header: Localization.kr.SIZE_ACTUAL,   clickable: false },
    { accessor: 'storageDomain',header: Localization.kr.DOMAIN,        clickable: false, width: '15%' },
    { accessor: 'interface',    header: '인터페이스',                  clickable: false },
    { accessor: 'readonly',     header: 'R/O',                         clickable: false, width: '6%' },
    { accessor: 'bootable',     header: 'bootable',                    clickable: false, width: '6%' },
    { accessor: 'sharable',     header: Localization.kr.IS_SHARABLE,   clickable: false, width: '6%' },
  ],
  // ---------------------------------------------------------------


  LUNS: [
    { accessor: 'name',        clickable: true,   header: Localization.kr.NAME, },
    { accessor: 'status',      clickable: false,  header: Localization.kr.STATUS, },
    { accessor: 'role',        clickable: false,  header: Localization.kr.ROLE, },
    { accessor: 'description', clickable: false,  header: Localization.kr.DESCRIPTION, },
  ],
  LUN_SIMPLE: [
    { accessor: 'logicalName',       header: Localization.kr.NAME,        },
    { accessor: 'description',       header: Localization.kr.DESCRIPTION, },
  ],
  LUN_DISK:  [
    { accessor: 'alias',             clickable: true,   header: Localization.kr.NAME, width:'10%' },
    { accessor: 'id',                clickable: false,  header: 'ID',  },
    { accessor: 'icon1',             clickable: false,  header: '', width:'4%' },
    { accessor: 'connectionTarget',  clickable: false,  header: `${Localization.kr.CONNECTION} ${Localization.kr.TARGET}`, },
    { accessor: 'storageDomain',     clickable: false,  header: Localization.kr.DOMAIN,          },
    { accessor: 'virtualSize',       clickable: false,  header: Localization.kr.SIZE_VIRTUAL,    },
    { accessor: 'lunId',             clickable: false,  header: 'LUN ID',                        },
    { accessor: 'serial',            clickable: false,  header: '시리얼',                         },
    { accessor: 'vendorId',          clickable: false,  header: `${Localization.kr.VENDOR} ID`,  },
    { accessor: 'productId',         clickable: false,  header: `${Localization.kr.PRODUCT} ID`, },    
    { accessor: 'description',       clickable: false,  header: Localization.kr.DESCRIPTION,     },
  ],

  CLUSTER_VM:[
    { accessor: "icon",    header: Localization.kr.STATUS,  clickable: false,   width: DEFAULT_WIDTH_ICON_COLUMN  },
    { accessor: 'name',    header: Localization.kr.NAME,    clickable: false,  },
    { accessor: 'status',  header: Localization.kr.STATUS,  clickable: false,  },
    { accessor: 'upTime',  header: Localization.kr.UP_TIME, clickable: false,  },
    { accessor: "cpu",     header: Localization.kr.CPU, clickable: false,  },
    { accessor: 'memory',  header: Localization.kr.MEMORY, clickable: false,  },
    { accessor: 'network', header: Localization.kr.NETWORK, clickable: false,  },
    { accessor: 'ipv4',    header: Localization.kr.IP_ADDRESS, clickable: false,  },
  ],
  CLUSTERS_POPUP: [
    { header: Localization.kr.NAME, accessor: 'name', clickable: false },
    { header: '모두 할당', accessor: 'allAssigned', clickable: false, width:80 },
    { header: '모두 필요', accessor: 'allRequired', clickable: false, width:80 },
    { header: `${Localization.kr.VM} 네트워크 관리`, accessor: 'vmNetMgmt', clickable: false, width:130 },
    { header: '네트워크 출력', accessor: 'networkOutput', clickable: false },
    { header: `${Localization.kr.MIGRATION} ${Localization.kr.NETWORK}`, accessor: 'migrationNetwork', clickable: false, width:130},
    { header: 'Gluster 네트워크', accessor: 'glusterNetwork', clickable: false },
    { header: '기본 라우팅', accessor: 'defaultRouting', clickable: false },
  ],
  HOSTS_DISCONNECTION: [
    { header: Localization.kr.STATUS, accessor: "icon", clickable: false /* width: DEFAULT_WIDTH_ICON_COLUMN */ },
    { header: Localization.kr.NAME, accessor: 'name', clickable: false },
    { header: Localization.kr.CLUSTER, accessor: 'cluster', clickable: false },
    { header: Localization.kr.DATA_CENTER, accessor: 'dataCenter', clickable: false },
  ],
  HOSTS_ALT: [
    { header: Localization.kr.STATUS, accessor: 'status', clickable: false },
    { header: '', accessor: 'iconWarning', clickable: false },
    { header: '', accessor: 'iconSPM', clickable: false },
    { header: Localization.kr.NAME, accessor: 'name', clickable: true },
    { header: Localization.kr.COMMENT, accessor: 'comment', clickable: false },
    { header: `${Localization.kr.HOST} 이름/IP`, accessor: 'address', clickable: false },
    { header: Localization.kr.CLUSTER, accessor: 'cluster', clickable: true }, // 클러스터 컬럼에 clickable 추가
    { header: Localization.kr.DATA_CENTER, accessor: 'dataCenter', clickable: false },
    { header: `${Localization.kr.VM} 수`, accessor: 'vmCount', clickable: false },
    { header: Localization.kr.MEMORY, accessor: 'memoryUsage', clickable: false },
    { header: Localization.kr.CPU, accessor: 'cpuUsage', clickable: false },
    { header: Localization.kr.NETWORK, accessor: 'networkUsage', clickable: false },
    { header: 'SPM', accessor: 'spmStatus', clickable: false },
  ],
  HOSTS_FROM_CLUSTER: [
    { header: Localization.kr.STATUS, accessor: "icon", clickable: false /* width: DEFAULT_WIDTH_ICON_COLUMN */ },  // 이모티콘 칸
    { header: Localization.kr.NAME, accessor: 'name', clickable: false },
    { header: `${Localization.kr.HOST} 이름/IP`, accessor: 'hostNameIP', clickable: false },
    { header: Localization.kr.STATUS, accessor: 'status', clickable: false },
    { header: '불러오기', accessor: 'loading', clickable: false },
    { header: '디스플레이 주소 덮어쓰기', accessor: 'displayAddress', clickable: false }
  ],
  HOSTS_ALL_DATA: [
    { header: Localization.kr.NAME, accessor: 'name', clickable: false },
    { header: Localization.kr.COMMENT, accessor: 'comment', clickable: false },
    { header: `${Localization.kr.HOST} 이름/IP`, accessor: 'hostNameIP', clickable: false },
    { header: Localization.kr.CLUSTER, accessor: 'clusterVo', clickable: true },
    { header: Localization.kr.DATA_CENTER, accessor: 'dataCenterVo', clickable: true },
    { header: Localization.kr.STATUS, accessor: 'status', clickable: false },
    { header: Localization.kr.VM, accessor: 'vm', clickable: false },
    { header: Localization.kr.MEMORY, accessor: 'memory', clickable: false },
    { header: Localization.kr.CPU, accessor: Localization.kr.CPU, clickable: false },
    { header: Localization.kr.NETWORK, accessor: 'network', clickable: false },
    { header: 'SPM', accessor: 'spmStatus', clickable: false }
  ],
  VM_CHART:[
    { header: Localization.kr.STATUS, accessor: "icon", clickable: false /* width: DEFAULT_WIDTH_ICON_COLUMN */ },  // 이모티콘 칸
    { header: Localization.kr.NAME, accessor: 'name', clickable: true },
    { header: Localization.kr.COMMENT, accessor: 'comment', clickable: false },
    { header: Localization.kr.HOST, accessor: 'hostVo', clickable: true },
    { header: Localization.kr.IP_ADDRESS, accessor: 'ipv4', clickable: false },
    { header: 'FQDN', accessor: 'fqdn', clickable: false },
    { header: Localization.kr.CLUSTER, accessor: 'clusterVo', clickable: true },
    { header: Localization.kr.STATUS, accessor: 'status', clickable: false },
    { header: Localization.kr.DATA_CENTER, accessor: 'dataCenterVo', clickable: true },
    { header: Localization.kr.MEMORY, accessor: 'memory', clickable: false },
    { header: Localization.kr.CPU, accessor: Localization.kr.CPU, clickable: false },
    { header: Localization.kr.NETWORK, accessor: 'network', clickable: false },
    { header: Localization.kr.UP_TIME, accessor: 'upTime', clickable: false },
    { header: Localization.kr.DESCRIPTION, accessor: 'description', clickable: false },
  ],
  
  VM_BRING_POPUP:[
    { header: Localization.kr.NAME, accessor: 'name', clickable: false },
  ],
  
  
  SNAPSHOT_NEW:[
    { header: '', accessor: 'check', clickable: false, width:'6%'},
    { header: Localization.kr.NAME, accessor: 'alias', clickable: false },
    { header: Localization.kr.DESCRIPTION, accessor: 'description', clickable: false }
  ],
  PERMISSIONS: [
    { header: Localization.kr.STATUS, accessor: "icon", clickable: false /* width: DEFAULT_WIDTH_ICON_COLUMN */ },
    { header: Localization.kr.USER, accessor: 'user', clickable: false },
    { header: '인증 공급자', accessor: 'provider', clickable: false },
    { header: '네임스페이스', accessor: 'nameSpace', clickable: false },
    { header: Localization.kr.ROLE, accessor: 'role', clickable: false },
    { header: Localization.kr.DATE_CREATED, accessor: 'createDate', clickable: false },
    { header: 'Inherited From', accessor: 'inheritedFrom', clickable: false },
  ],
  AFFINITY_GROUP:[
    { header: Localization.kr.STATUS, accessor: 'status', clickable: false },
    { header: Localization.kr.NAME, accessor: 'name', clickable: false },
    { header: Localization.kr.DESCRIPTION, accessor: 'description', clickable: false },
    { header: '우선 순위', accessor: 'priority', clickable: false },
    { header: `${Localization.kr.VM} 측 극성`, accessor: 'vmConfig', clickable: false },
    { header: `${Localization.kr.VM} 강제 적용`, accessor: 'vmEnforce', clickable: false },
    { header: `${Localization.kr.HOST} 측 극성`, accessor: 'hostConfig', clickable: false },
    { header: `${Localization.kr.HOST} 강제 적용`, accessor: 'hostEnforce', clickable: false },
    { header: `${Localization.kr.VM} 멤버`, accessor: 'vmMember', clickable: false },
    { header: `${Localization.kr.VM} 레이블`, accessor: 'vmLabel', clickable: false },
    { header: `${Localization.kr.HOST} 멤버`, accessor: 'hostMember', clickable: false },
    { header: `${Localization.kr.HOST} 레이블`, accessor: 'hostLabel', clickable: false },
  ],
  AFFINITY_LABELS: [
    { header: Localization.kr.NAME, accessor: 'name', clickable: false },
    { header: `${Localization.kr.VM} 멤버`, accessor: 'vmMember', clickable: false },
    { header: `${Localization.kr.HOST} 멤버`, accessor: 'hostMember', clickable: false },
  ],

  EVENTS: [
    { accessor: '_severity',   header: Localization.kr.STATUS,   clickable: false, width: 30 },
    { accessor: 'time',        header: Localization.kr.TIME,    clickable: false, width: 100 },
    { accessor: 'description', header: Localization.kr.MESSAGE, clickable: false, width: 640 },
  ],

  JOBS: [
    { header: Localization.kr.NAME, accessor: 'name', clickable: false }
  ],
  JOB_HISTORY_COLUMNS : [
    { header: '작업명', accessor: '_description', style: { paddingLeft: "20px" }, width: 150 },
    { header: '세부작업', accessor: 'numSteps',align: "center", width: DEFAULT_WIDTH_ICON_COLUMN },
    { header: `${Localization.kr.START} ${Localization.kr.TIME}`,  accessor: 'startTime'},
    { header: `${Localization.kr.END} ${Localization.kr.TIME}`,  accessor: 'endTime'},
    { header: Localization.kr.STATUS,          accessor: 'status', width: DEFAULT_WIDTH_ICON_COLUMN ,align: "center"  },
    { header: Localization.kr.TIMESTAMP,       accessor: 'timestamp' , width: DEFAULT_WIDTH_ICON_COLUMN  },
  ],
  PROVIDER: [
    { accessor: '_name',        header: Localization.kr.NAME,   clickable: false },
    { accessor: 'type',        header: Localization.kr.TYPE,    clickable: false },
    { accessor: 'description', header: Localization.kr.DESCRIPTION, clickable: false },
    { accessor: 'providerUrl', header: "공급자 URL", clickable: false },
  ],
  // 사용자
  SETTING_USER: [
    { header: Localization.kr.STATUS, accessor: "icon", clickable: false , width: DEFAULT_WIDTH_ICON_COLUMN },
    { header: Localization.kr.USER_ID, accessor: 'username', clickable: false },
    { header: Localization.kr.NAME, accessor: 'firstName', clickable: false },
    { header: '성', accessor: 'surName', clickable: false },
    { header: '비활성화 여부', accessor: '_isDisabled', clickable: false },
    { header: '인증 공급자', accessor: 'authProvider', clickable: false },
    { header: '네임스페이스', accessor: 'namespace', clickable: false, width:'8%'  },
    { header: Localization.kr.EMAIL, accessor: 'email', clickable: false },
    { header: '가입일자', accessor: 'createDate', clickable: false },
  ],
  SETTING_PROVIDER_TOKEN :[
    { header: "UUID", accessor: "uuid", clickable: false },
    { header: "유형", accessor: "type", clickable: false },
    { header: "설명", accessor: "description", clickable: false },
    { header: "생성일", accessor: "createdAt", clickable: false },
  ],
  // 활성사용사세션
  ACTIVE_USER_SESSION: [
    { header: '세션 DB ID', accessor: 'id', clickable: false },
    { header: Localization.kr.USER_ID, accessor: 'userName', clickable: false },
    { header: '인증 공급자', accessor: 'authzName', clickable: false },
    { header: '사용자 ID', accessor: 'userId', clickable: false },
    { header: '소스 IP', accessor: 'sourceIp', clickable: false },
    { header: `세션 시작 ${Localization.kr.TIME}`, accessor: 'sessionStartTime', clickable: false },
    { header: '마지막 세션 활성', accessor: 'lastSessionActive', clickable: false },
  ],

  //설정 (역할)
  SETTING_ROLE: [
    { header: Localization.kr.STATUS, accessor: "icon", clickable: false /* width: DEFAULT_WIDTH_ICON_COLUMN */ },
    { header: Localization.kr.NAME, accessor: 'name', clickable: false },
    { header: Localization.kr.DESCRIPTION, accessor: 'description', clickable: false },
  ],
  //설정(인스턴스유형)
  SETTING_INSTANCE:[
    { header: Localization.kr.NAME, accessor: 'name', clickable: false }
  ],
   //설정(시스템권한)
  SETTING_SYSTEM: [
    { header: Localization.kr.STATUS, accessor: "icon", clickable: false /* width: DEFAULT_WIDTH_ICON_COLUMN */ },
    { header: Localization.kr.USER_ID, accessor: 'user', clickable: false },
    { header: '인증 공급자', accessor: 'provider', clickable: false },
    { header: '네임스페이스', accessor: 'nameSpace', clickable: false },
    { header: Localization.kr.ROLE, accessor: 'role', clickable: false }
  ],
  //설정 시스템권한 추가팝업(사용자)
  SETTING_POPUP_USER:[
    { header: Localization.kr.NAME, accessor: 'name', clickable: false },
    { header: '성', accessor: 'lastName', clickable: false },
    { header: Localization.kr.USER_ID, accessor: 'username', clickable: false },
  ],
  SETTING_LICENSING:[
    { header: '라이센스', accessor: 'license', clickable: false },
    { header: '라이센스 키', accessor: 'licenseKey', clickable: false },
    { header: Localization.kr.PRODUCT, accessor: 'product', clickable: false },
    { header: Localization.kr.STATUS, accessor: 'status', clickable: false },
    { header: '만료', accessor: 'expiration', clickable: false }
  ],
  SETTING_CERTIFICATES: [
    // { header: 'ID', accessor: 'id', clickable: false },
    { accessor: 'alias',    clickable: true,  header: Localization.kr.NAME },
    { accessor: 'address',  clickable: false, header: Localization.kr.ADDRESS },
    { accessor: 'dday',     clickable: false, header: Localization.kr.DAYS_REMAINING },
    { accessor: 'notAfter', clickable: false, header: Localization.kr.DATE_EXPIRATION },
    // { header: '버전', accessor: 'version', clickable: false },
  ]
}

export default TableColumnsInfo;