version: "3"

services:
  rutil-vm-api:
    image: rutil-vm-api:latest
    container_name: rutil-vm-api
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - "6690:6690"    
    environment:
      TZ: Asia/Seoul
      LANGUAGE: ko_KR;ko;en_US;en
      LC_ALL: ko_KR.UTF-8
      LANG: ko_KR.utf8
      RUTIL_VM_OVIRT_IP: 192.168.0.70
      RUTIL_VM_OVIRT_PORT_HTTPS: 8443
      RUTIL_VM_PORT_HTTPS: 6690
      RUTIL_VM_SSL_KEY_STORE: /app/certs/keystore.p12
      RUTIL_VM_SSL_KEY_STORE_PASSWORD: rutil-vm-api
      RUTIL_VM_SSL_KEY_ALIAS: rutil-vm-api
      RUTIL_VM_CORS_ALLOWED_ORIGINS: 192.168.0.70;localhost;rutil-vm;rutilvm-dev.ititinfo.com
      RUTIL_VM_CORS_ALLOWED_ORIGINS_PORT: 3000;3443;443
      RUTIL_VM_OVIRT_LOGIN_LIMIT: 5
      RUTIL_VM_OVIRT_SSH_JSCH_LOG_ENABLED: true
      RUTIL_VM_OVIRT_SSH_JSCH_CONNECTION_TIMEOUT: 60000
      RUTIL_VM_OVIRT_SSH_CERT_LOCATION: /app/tmp
      RUTIL_VM_OVIRT_SSH_PRVKEY_LOCATION: /root/.ssh/id_rsa
      RUTIL_VM_OVIRT_SSH_ENGINE_ADDRESS: rutilvm@192.168.0.70:22
      RUTIL_VM_OVIRT_SSH_ENGINE_PRVKEY: |
        Bag Attributes
            localKeyID: 77 12 A1 5B 32 2A EA D2 EC 62 03 FE DC 95 CC A3 B2 B4 FA 38 
        Key Attributes: <No Attributes>
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCVNAfVs+9YDbNa
        0jToyQUDinB/EF1u+AbCMLc5wFWAVWmSqglhUcLYZMZSL2xvAcPTmFTcWeBrUMff
        01hB4EkdbX98gDBVg8taN3BmOQmdgYsj+GSkalLNzcxkWHBhOl42cGmz/zWk8oKB
        Y9ZRgf+O7lCApTnqWoGwINtLBLESbZ1o4XW/1ECJgr63S4edI5tcEsh/V0gvto1l
        9q3qwrB+hHnjwz6VP6AvZxy3eSx+gGp47YCqcixxdT3qCvuzXgjOrU5V7YhHBs4C
        TwCmmp+KhuFe2wI7g0X7WTgKztebCaP8A/WioXX/9i1Zj2sj+u7mnhQ8MIyEcaIk
        QiQPntU5AgMBAAECggEAaxMD7GFNCqwKYssoHUblyjy3rvhXlSN59jJvy4oz0f15
        3j8YrDa41gK8MI7ICoIBvwA7Jkd5vooiZoaNd/k1f2DtdLOp/DSw4vWWPEYCmH43
        FIFV+Ig1FGz0ma6+N4hjxD24Heyw2scO0TyMucHJXRG5xBjPD1gUagmqVpPvX4Ei
        R6/gc2ENZnZQHlhmP9N16YHEOrzhC/x25Oa2aKdaVQzB3QtwMDczcBAiuXkazZyR
        LGYwjUPZ9eSYVwYrP3pjp4Qc8Rn4KjwRm4hL9hrQNfSdxxvJ2DeONapZ70cxtJI2
        BJdlXhq/mDGfBTPE9NG/c1IXD4rlP/TysPBIOaVwAQKBgQDFPVFYnD771zArydzw
        /VEvkdjfXkzVtSNLrt3S2YGpvwkLQV4et+fVPTKhE+mwy61jCpHwx/dws2eF8wtB
        snPf7kq8pA/Ec7Jsv0kc/bvODYtAVcLlPLLw/4fGxbKUSaJokQNdbthBhjV2oN53
        537gsEkMg8PinlxofAEBhHRfwQKBgQDBpyzJjwsj0qf5GhAHDkkuGnsnMw/07zOo
        /wCrm2Pu3IgQ6oUZ91evj3guE6rkpgaMlfymo8th8YgLroxoU4g1161l/a8I0jfL
        KjxStSgdCMdxKNRwfhZym/kSB1BsnxwEH2EJIKtNXgIULM9gUBY5d9vU+1ea/awX
        9w3rfhJTeQKBgQC6CzmEpHSAZhyo4RKHOdnvTdnL74338pDlXX8c2E8GxwwH0tOt
        k/iYWc48w6SlP6k/h4PbIzNR2ddnMLZIdMP50DIst2+r9Rmym8eiEe+oz3uu5nYc
        dmGvEsiGhIoKd1461bXf1qMjQy2AxQKzBOfXllCA/nSxeIBficAFJ2QBwQKBgHoP
        QS+aNc9SjAV64/dOjdm9XzqJ+NjNnKY8dNO1kfuQjUL8TwDa4i4KJBoG04RjEWWz
        dBgkzaDieHnEf0OSwxwM4YKTr6vDtN8ds//9p1cFnZA5yA1PrB55KTiv24VblHEU
        xjjWmqKdSnok9GEkmZ2HasyHz+QlWD+SvPdd83chAoGAUdUfXA6M1lgP8l+WmKAi
        7BR3lx66x237M5qRmdVEZo1OK+aMOBsyfQY56Wb3+6ULibSN6XoGWKc0POeg1L4t
        TIACwgvXc72qLc/g/T6EL67nJO0j4CYe6abaKujXmgJLWi0PR9wqO60uD/v7xbPG
        NwxYrCW6ZS/zEq0Ep976vvU=
        -----END PRIVATE KEY-----
      POSTGRES_JDBC_PORT: 5432
      POSTGRES_DATASOURCE_JDBC_ID: rutil
      POSTGRES_DATASOURCE_JDBC_PW: rutil1!
    volumes:
      - ./rutil-vm-api/logs:/app/logs:rw
      - ./rutil-vm-api/certs:/app/certs:rw
      - ./rutil-vm-api/tmp:/app/tmp:rw
      # - /root/.ssh:/root/.ssh:rw
      - /home/rutilvm/.ssh:/root/.ssh:rw
      - /etc/hosts:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ovirt_network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail https://localhost:6690/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: on-failure

  rutil-vm:
    image: rutil-vm:latest
    container_name: rutil-vm
    ports:
      - "443:443"
    environment:
      TZ: Asia/Seoul
      LANGUAGE: ko_KR;ko;en_US;en
      LC_ALL: ko_KR.UTF-8
      LANG: ko_KR.utf8
      NODE_ENV: production
      __RUTIL_VM_OVIRT_IP_ADDRESS__: 192.168.0.70
      __RUTIL_VM_LOGGING_ENABLED__: true
      __RUTIL_VM_ITEMS_PER_PAGE__: 20
    volumes:
      - ./rutil-vm/certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/pki/ovirt-engine/keys:/etc/pki/ovirt-engine/keys:ro
    networks:
      - ovirt_network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail https://localhost:433 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: always
    
  rutil-vm-wsproxy:
    image: rutil-vm-wsproxy:latest
    container_name: rutil-vm-wsproxy
    ports:
      - "9999:9999"
    environment:
      TZ: Asia/Seoul
      LANGUAGE: ko_KR;ko;en_US;en
      LC_ALL: ko_KR.UTF-8
      LANG: ko_KR.utf8
      PORT: 9999
    volumes:
      - ./rutil-vm/certs/fullchain.pem:/home/node/fullchain.pem:ro
    networks:
      - ovirt_network
    restart: always # undefined으로 인자가 갈 때 죽음

networks:
  ovirt_network:
    driver: bridge