version: "3"

services:
  rutil-vm-api:
    image: ititcloud/rutil-vm-api:latest
    container_name: rutil-vm-api
    ports:
      # - "8080:8080"
      - "6690:6690"
    environment:
      TZ: Asia/Seoul
      LANGUAGE: ko_KR;ko;en_US;en
      LC_ALL: ko_KR.UTF-8
      LANG: ko_KR.utf8
      RUTIL_VM_OVIRT_IP: 192.168.0.180
      RUTIL_VM_OVIRT_PORT_HTTPS: 8443
      RUTIL_VM_PORT_HTTPS: 6690
      RUTIL_VM_CORS_ALLOWED_ORIGINS: 192.168.0.180;localhost;rutil-vm
      RUTIL_VM_CORS_ALLOWED_ORIGINS_PORT: 3000;3443;443
      RUTIL_VM_OVIRT_SSH_JSCH_LOG_ENABLED: true
      RUTIL_VM_OVIRT_SSH_PRVKEY_LOCATION: /root/.ssh/id_rsa
      RUTIL_VM_OVIRT_SSH_ENGINE_ADDRESS: root@192.168.0.180:22
      RUTIL_VM_OVIRT_SSH_ENGINE_PRVKEY: |
        Bag Attributes
            localKeyID: 89 F1 F6 B8 51 E7 3B AD 1F C6 06 20 3E A9 4E 47 EF 33 9A 8F 
        Key Attributes: <No Attributes>
        -----BEGIN PRIVATE KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC61lAtrEkfkLI5
        m+AHlWSRJ0Rr0qHwEAQSu9IXzTcxmH7N7L3AdepOK29UzOSRZKznBW9CR49y4j24
        AV9eUKgz3X4B+tOdR3VLpHr1xN9MQKgWhBMB15173cw1B7gSy6gBR6mQBuKN+Wo/
        N4kkZbd823ly4RcvACdZtlBNJTXpKVYLZIRRft6q+gNiYLqdfLcz3KgatzZFcF7C
        n0Q/MRroG+1E2tmLJz0NzKh8Sp2bQTTm6bKEaunloQAETaCqkmeLdWK7X6TB7xSN
        miRpfmla8DV55fCiPS6EIFrHxhkkHvWipI87UHT+eLO+RhIYFIP0ti2vzZWGPUJh
        gNk8O5kbAgMBAAECggEAdNwdNCQBbJPVVcEQI84mI7/6xLHvBbcOxSTi6G476nJm
        RaigmqNmFNSIAvNQtzvQBYNZrowRxhqJ3fBF1Tj/q8kKynQ3LbWHQPO00Mn9nLUI
        LWUYeluBLftxgW29jUwCXiKThPk5dPGeqcGzrqdMV/Tyho8RMB2ZfzxQB6CRkq5t
        GMT1KkeEt0HVwaJwqFi1EwSeIQHhjWk7IF1jNrtpzTuOAg89nmsV5X9U3H5JNY8n
        k1clKO0MoNMQQ8SueQwenOhdD/nEudVm36mcasBMruk3AzVp6hLyF8xLsF4Y0A5A
        s2Vn1cxYoiwFqtdW9Eg8lwTo/eHss3QmrrATD2a+yQKBgQDnLyO+U1vGd67qMVFD
        qxzYGM9rMKgCL5o8PIMbGmTK3aHOw0X1qt8B7ORLlacns01iOwCNOiNIYSDcaO43
        ddEIA1PYf7JExctsHvz87ZCSgZ2gecXGZruK/zxVrqXrCG63871ltcL1Hh/sOYHg
        krBkoNdvGrjRe5CreCdl5JlZ5QKBgQDO5IiukLJnpEK6yplm9DbuXVWwPeoj+H3E
        YpiegRFumFLdufMruU6nx7lHDMCj7a7uNC8whMpcGibWXc6gEo8NBnkZUQMcpp84
        9bVndVrEP8oXkVm+4SAsiSdfRP5sXC7XJO6GIBWrM+xWYueK/9wWsFWhIYTjyLgB
        SDKpqSX2/wKBgDsF0f5ZkejNzZ6FENZR7X9OdkZLmdlVBe+zE1XsGyegBhufx1C9
        W0pGjNKvVonQQUV/AtkLqs5j3dvn/kmyjreZAeMYVw8v4IuuLbD1hh+hb/j0ngXV
        XLRUDbdia4HiGUJlvEknaqriEgxhckM/sEFAvz/idqUlAv6EIqrk/jHxAoGBAJLg
        j2BOfTky1eTB/BGpAm5KeJC8A8MxoCeRT4QHYRbAsOOUJVw/G+Xk1lXoacJ29J9L
        EM1DGF42eqfoxM3DHydCFyqv5qOqbpMDbJtcJun310LP/4SRUkQLwpXR50WKU/6M
        y4EQuhFmtTvGz1ZQujCpUsEniK4lSuwuEzl7SeaFAoGBAKyasjepgyH3dK+sigVu
        Gp0X34N+Gszbs2qGMw6AYc5nCbp/bX2JfgiR2wzAm8d4QP8Fonk5/cdnC1HWZOyB
        0Jo9cyI6oAHlzRf0HABNQ8Ith9SvsWT1i43xEcgd3gCTNnS0jo9JJ9wwPpoDcQ7a
        4axM7iTqF6hQ8O5RWY8AFkaB
        -----END PRIVATE KEY-----
      POSTGRES_JDBC_PORT: 5432
      POSTGRES_DATASOURCE_JDBC_ID: rutil
      POSTGRES_DATASOURCE_JDBC_PW: rutil1!
    volumes:
      - ./rutil-vm-api/logs:/app/logs:rw
      - /root/.ssh:/root/.ssh:rw
      - /etc/hosts:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ovirt_network
#    healthcheck:
#      test: ["CMD-SHELL", "curl --silent --fail localhost:9600 || exit 1"]
#      interval: 10s
#      timeout: 10s
#      retries: 3
    restart: on-failure

  rutil-vm:
    image: ititcloud/rutil-vm:latest
    container_name: rutil-vm
    ports:
      - "3433:443"
    environment:
      - TZ=Asia/Seoul
      - LANGUAGE=ko_KR;ko;en_US;en
      - LC_ALL= ko_KR.UTF-8
      - LANG=ko_KR.utf8
    networks:
      - ovirt_network
#    healthcheck:
#      test: ["CMD-SHELL", "curl --silent --fail localhost:9600 || exit 1"]
#      interval: 10s
#      timeout: 10s
#      retries: 3
    restart: on-failure
    
#  httpd:
#    image: httpd:2.4.37-alpine
#    platform: linux/amd64
#    container_name: httpd
#    ports:
#      - "8080:80"
#      - "443:443"
#    volumes:
#      - /etc/httpd/conf:/etc/httpd/conf:ro
#      - /etc/httpd/conf.d:/etc/httpd/conf.d:ro
#      - /etc/httpd/conf.modules.d:/etc/httpd/conf.modules.d:ro
#      - /etc/httpd/logs:/etc/httpd/logs:ro
#      - /etc/httpd/modules:/etc/httpd/modules:ro
#      - /etc/pki/ovirt-engine/certs:/etc/pki/ovirt-engine/certs:ro
#      - /etc/pki/ovirt-engine/keys:/etc/pki/ovirt-engine/keys:ro
#      - /etc/pki/ovirt-engine/apache-ca.pem:/etc/pki/ovirt-engine/apache-ca.pem:ro
#      - /usr/share/httpd:/usr/share/httpd:ro
#      - /var/www:/var/www:ro
#    depends_on:
#      - rutil-vm-api
#    networks:
#      - ovirt_network

networks:
  ovirt_network:
    driver: bridge