version: "3"

services:
  rutil-vm-api:
    image: rutil-vm-api:latest
    container_name: rutil-vm-api
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - "6690:6690"
    environment:
      TZ: Asia/Seoul
      LANGUAGE: ko_KR;ko;en_US;en
      LC_ALL: ko_KR.UTF-8
      LANG: ko_KR.utf8
      RUTIL_VM_OVIRT_IP: 192.168.0.55
      RUTIL_VM_OVIRT_PORT_HTTPS: 8443
      RUTIL_VM_PORT_HTTPS: 6690
      RUTIL_VM_SSL_KEY_STORE: /app/certs/keystore.p12
      RUTIL_VM_SSL_KEY_STORE_PASSWORD: rutil-vm-api
      RUTIL_VM_SSL_KEY_ALIAS: rutil-vm-api
      RUTIL_VM_CORS_ALLOWED_ORIGINS: 192.168.0.55;localhost;rutil-vm;rutilvm-engine
      RUTIL_VM_CORS_ALLOWED_ORIGINS_PORT: 3000;3443;443
      RUTIL_VM_OVIRT_LOGIN_LIMIT: 5
      RUTIL_VM_OVIRT_SSH_JSCH_LOG_ENABLED: true
      RUTIL_VM_OVIRT_SSH_JSCH_CONNECTION_TIMEOUT: 60000
      RUTIL_VM_OVIRT_SSH_CERT_LOCATION: /app/tmp
      RUTIL_VM_OVIRT_SSH_PRVKEY_LOCATION: /root/.ssh/id_rsa
      RUTIL_VM_OVIRT_SSH_ENGINE_ADDRESS: rutilvm@192.168.0.55:22
      RUTIL_VM_OVIRT_SSH_ENGINE_PRVKEY: |
        Bag Attributes
            localKeyID: D9 45 F4 E3 DB F2 3E F8 3F 38 70 5D C6 4B 51 F0 40 A0 5B 4B 
        Key Attributes: <No Attributes>
        -----BEGIN PRIVATE KEY-----
        MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC5vUQayNUslENs
        V2Bjcr94/C+AvqnGpP1JAxCZtvb8aL8wPW7PmazkPeKKnGiXooG1rOAGSdORWzNL
        3vXix/u5In4d2uw8J/0eW/tIGfQ2KR9GKhR6SJeTSFTh9medM4619x4RFu5wAyBf
        ESpS3qBSb3ateGyvNR03DbclxZsrtWJC0FiQIGqBT8ln0FflWeb1Bl1HWsZb541M
        wV58ohfXha1fH2yh64rJQw84o3YoQijIvOPxlS+4hnlvH1v5FbSKGZzJWdM5uxGq
        dL/yPDZQTQXD/ifpeUcu4GkpC0bre/hR4IVtZ9xXkP7/l6ggSryRpWhHcAuBZCgQ
        B2oAHgD5AgMBAAECggEBAIeFi02nv7LZMyC32EJ3lTFngBmGBEZGV/CP5eriTu/4
        VZeTG2kqDbYzWTodyUrqbY3rZ0HvWAk07Aat1eb0V7zLaA3MkJWL7+nY303Kch+a
        fZEqXuqiUMZL/nMo4I0Y80Xd2vhJLQxZm6MB2UnB2mSLo6IKvfJQ5NIolbtfpUqL
        vCAvv4Ya/mdSsJ+Mc5VdK6gN/4kzr+ZGJHzfgIjcptHSzdI8viyLgmnGx92tI/wV
        MpXGMeCBV+LTRs16wLxjQQvpOshUp18Xh2K9I4l4Tz8LFOAcLsGDVDRGESkGODlL
        cXux9HGryrfLHjZUd5c8ee6kjPoBwetBP7X2L/58tOkCgYEA8U8vmbjEQE9cwMyk
        zY+LeuHupoMR9fiFFP7MQlU0WJLnxewHuuEb+fM9k8eM+U5skdpJIJICsZmtgaxF
        aCAw8GP0uivdOggTrseVUsAkz4vtIPL82DoWz4pqffYpdZxxl8EMx7DC61cRFLeI
        wJS+2hGcqzNc+DeaH/sGJJPzOGsCgYEAxQwFDXylMkRGOrcA0rIkSfng/cVZPmfT
        88D8VHCuc+3eWmAzsQ+eMzynpUiF+TsMyuu0+6WfkyjMj2H2tgnu1YVJkIkf4AYd
        AMYsqtLMLdcL2llbQiRcbhJ/a0ttLTu0eretE5Q727UZmLSuBotSOwhTBxLGZqkI
        5kMUMO+YVSsCgYEAwplcRrh1M3OM1kJySP+QuPlIjum2a0kOcZ8FNB0oSKG33an5
        leCBwjFBoFJVwptW/MwvGuAE4hqPjLpTgqQrM0E4k4ZaMrlevh1fs0sWpHUwNtkd
        xHYb/SSfupLwXlNaW8ooN0W5+zXMpYtY8g1CV/PKB1o1iEq2tUGnc4oIo58CgYBc
        VlibzFhBaPscEpvhIDefLuh/IxbCBretFzdnfnJRwxsacNBoXbA9xGOvMYAOndxN
        zwy9jAxuUoUhf7+z6I2yI0ao44k7WsIGlddiqWui444bYRpBsXZa4nIxXmQn+T2G
        8EG71hAC0ifPhoOyb2E2Zp05yFOO0hFojfCNSgmxhwKBgQDwsittWc1OSUvmFNfz
        weCK7trIV0zuTiIUXeYchTzSqhGz5vIZU+KSt9sGllfrzEvTHbkVIa1D8v1saFuB
        QYtSTmsZUR6/m7G/c5wo2va0OWGY7kbCRYnZLttjM3Ny5mXg6ZfZH1EeXBjhNOhj
        WajFFSz6JqxQudsaQGlcEFZfGA==
        -----END PRIVATE KEY-----
      POSTGRES_JDBC_PORT: 5432
      POSTGRES_DATASOURCE_JDBC_ID: rutil
      POSTGRES_DATASOURCE_JDBC_PW: rutil1!
    volumes:
      - /opt/rutilvm/rutil-vm-api/logs:/app/logs:rw
      - /opt/rutilvm/rutil-vm-api/certs:/app/certs:rw
      - /opt/rutilvm/rutil-vm-api/tmp:/app/tmp:rw
      # - /root/.ssh:/root/.ssh:rw
      - /home/rutilvm/.ssh:/root/.ssh:rw
      - /etc/hosts:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ovirt_network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail https://localhost:6690/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  rutil-vm:
    image: rutil-vm:latest
    container_name: rutil-vm
    ports:
      - "443:443"
    environment:
      TZ: Asia/Seoul
      LANGUAGE: ko_KR;ko;en_US;en
      LC_ALL: ko_KR.UTF-8
      LANG: ko_KR.utf8
      NODE_ENV: production
      __RUTIL_VM_OVIRT_IP_ADDRESS__: 192.168.0.55
      __RUTIL_VM_LOGGING_ENABLED__: true
      __RUTIL_VM_ITEMS_PER_PAGE__: 20
    volumes:
      - /opt/rutilvm/rutil-vm/certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/pki/ovirt-engine/keys:/etc/pki/ovirt-engine/keys:ro
    networks:
      - ovirt_network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail https://localhost:433 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    
  rutil-vm-wsproxy:
    image: rutil-vm-wsproxy:latest
    container_name: rutil-vm-wsproxy
    ports:
      - "9999:9999"
    environment:
      TZ: Asia/Seoul
      LANGUAGE: ko_KR;ko;en_US;en
      LC_ALL: ko_KR.UTF-8
      LANG: ko_KR.utf8
      PORT: 9999
    volumes:
      - /opt/rutilvm/rutil-vm/certs/fullchain.pem:/home/node/fullchain.pem:ro
    networks:
      - ovirt_network
    restart: unless-stopped

networks:
  ovirt_network:
    driver: bridge