version: "3"

services:
  rutil-vm-api:
    image: rutil-vm-api:latest
    container_name: rutil-vm-api
    ports:
      - "6690:6690"
    environment:
      TZ: Asia/Seoul
      LANGUAGE: ko_KR;ko;en_US;en
      LC_ALL: ko_KR.UTF-8
      LANG: ko_KR.utf8
      RUTIL_VM_OVIRT_IP: 192.168.0.55
      RUTIL_VM_OVIRT_PORT_HTTPS: 8443
      RUTIL_VM_PORT_HTTPS: 6690
      RUTIL_VM_SSL_KEY_STORE: /app/certs/keystore.p12
      RUTIL_VM_SSL_KEY_STORE_PASSWORD: rutil-vm-api
      RUTIL_VM_SSL_KEY_ALIAS: rutil-vm-api
      RUTIL_VM_CORS_ALLOWED_ORIGINS: 192.168.0.55;ovirt45.test.local;localhost;rutil-vm
      RUTIL_VM_CORS_ALLOWED_ORIGINS_PORT: 3000;3443;443
      RUTIL_VM_OVIRT_LOGIN_LIMIT: 5
      RUTIL_VM_OVIRT_SSH_JSCH_LOG_ENABLED: true
      RUTIL_VM_OVIRT_SSH_JSCH_CONNECTION_TIMEOUT: 60000
      RUTIL_VM_OVIRT_SSH_CERT_LOCATION: /app/tmp
      RUTIL_VM_OVIRT_SSH_PRVKEY_LOCATION: /root/.ssh/id_rsa
      RUTIL_VM_OVIRT_SSH_ENGINE_ADDRESS: rutilvm@192.168.0.55:22
      RUTIL_VM_OVIRT_SSH_ENGINE_PRVKEY: |
        Bag Attributes
            localKeyID: D4 DF 99 FA 40 31 FF 0C E2 D6 D3 B2 FF 03 FD EA 54 63 29 AC 
        Key Attributes: <No Attributes>
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCz5KHD76kxEgxd
        Dm20+LrtZ/BmX4B7J/qBqBz3/p3Fr4dJ6Zoigog83cSeHwwvsPoKs1DWTOSQQDQk
        nQpjrU3UqX1/26mjgXoF9w48Vbyqs6nGjCA0k0K7cMc05PmWI5Bwe1ULU4jZnM9n
        Ikc9vKVwWJGhHcTXPTLX5F+v1tDBCmYPOGni0L/Gk3EJGa/dQ/uHUbIyRxqLmnd6
        0rD9kAJNr89ZuXn9gQg0mG/ujcPnhOYHwhEekONe2cYp82qxHoXv6fcAd4Axijkc
        tXgw4eFgsEpqXdCj5ZCQfBrVr6ZDaM1Y7heosfUZbe2iCn+5dTtjxZTO126GbjoH
        TMuCq0/5AgMBAAECggEAV49SOYd+h7bsM6MhPPPQMFvmBD450DgeU1ubdg4Fh0Iv
        jIdaka+NVmrvF7Ou/8uZePncv+I/YgMOHkAd3XRuLLOutTwa7s3Hsf2VfUKSCVhX
        q59q0YxX79ot7A4DedOnq0gslc28D4em3+EsYd1ffTZu88gElmtgQvsSpAjgJQT0
        stwSClA7+0JgvSfQeTfNs9ucFuhZvxM9UpQjN9ZRDNYwc/OjiWcZbJ1Td5VPU4ac
        GUolrAK0YYE10nJebaT0QWQN09hnIJUHBLbmZ1I+ZlyFJu5KKQEkBGPpsosG+Epo
        HqkHTIkIowj9c8agAha5hO25xs0Q5G7iKwmmacSHgQKBgQDdhpmzPxl/392knPXZ
        HmDN3y1wWNvse+QTLw68ImxC+W7d/lJ6lkCgwWF1JRf+6aDkPneLvCYqV81YuUD4
        M4tixhZMDsmdQOP02LD7UhPR6bHAsNbKzbdPuSjQHMQ07FZRDIJFhGjrxYnEgV3Y
        p5I0OrRdgVWp9wr1cxax6jgMaQKBgQDP42uf/zn4yva1GLZWETeQuWTB2WIO0sjG
        TYDVkMGv0J7L9TcO9s/FHbDaBS+zeUnkPOLPXFSmZBsD0lTpuxPrrneNH2v5g/H0
        7eoXbaqptPFEm2F4t4WBJt98VM5Qj+eSIHs2ugkIdd2PVxHKIHaFSADAGzixDfcO
        ushTbkL1EQKBgQCRH7rVeMMFyOz1CHbu9D3K4Shtb2k0Nb2m668lhQ+TmMEO4au6
        73ALYGSuT8y2jOuAW4QJoQsHtlmqhEKR14K7BLZawV1HjdlI8CSRoKWnYQe4CqHM
        XpR2wACCxjWrziCGHEHDtQjfXJvyhiWq56yaVtMOZspt/I/LWMhHaf+p8QKBgHOy
        xGFFcIQwoWFkoYYBCwW2yIbCbzqEwUzsMXmqmME6wEYO8VeYsUWpIpYUMNoX9LHb
        2PdDEbGRIR/dXXi/r3SJouudw0AY2P5RsujbFhJhK63dNEA1E04vzk2p/TEFBgJj
        pW9t1j0pK+fss2/k5VGEIzbHb6PKe+dsuLUGNqmhAoGAFX7Ps/fYRPXPnyo6/k9a
        gzy25cN27jLNzQfULZA2+X2YOKRex1Huz2egDouUCYgff0n+ec8E0/doExXrtNYi
        VYTCLjjpaPyGJI/Qvv8DVXEW78Jor3a3XLpjA8lv/4LJW6c5H8GTAq0Egpgewrqg
        tmCVyigA9078ZxAVdd0fJwk=
        -----END PRIVATE KEY-----
      POSTGRES_JDBC_PORT: 5432
      POSTGRES_DATASOURCE_JDBC_ID: rutil
      POSTGRES_DATASOURCE_JDBC_PW: rutil1!
    volumes:
      - /opt/rutilvm/rutil-vm-api/logs:/app/logs:rw
      - /opt/rutilvm/rutil-vm-api/certs:/app/certs:rw
      - /opt/rutilvm/rutil-vm-api/tmp:/app/tmp:rw
      - /home/rutilvm/.ssh:/root/.ssh:rw
      - /etc/hosts:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ovirt_network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail https://localhost:6690/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  rutil-vm:
    image: rutil-vm:latest
    container_name: rutil-vm
    ports:
      - "443:443"
    environment:
      TZ: Asia/Seoul
      LANGUAGE: ko_KR;ko;en_US;en
      LC_ALL: ko_KR.UTF-8
      LANG: ko_KR.utf8
      NODE_ENV: production
      __RUTIL_VM_OVIRT_IP_ADDRESS__: 192.168.0.55
      __RUTIL_VM_LOGGING_ENABLED__: true
      __RUTIL_VM_ITEMS_PER_PAGE__: 25
      __RUTIL_VM_IS_LICENCE_VERIFIED__: false
      __RUTIL_VM_WATERMARK_TEXT__: 무단배포금지
    volumes:
      - /opt/rutilvm/rutil-vm/certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/pki/ovirt-engine/keys:/etc/pki/ovirt-engine/keys:ro
    networks:
      - ovirt_network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail https://localhost:433 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    
  rutil-vm-wsproxy:
    image: rutil-vm-wsproxy:latest
    container_name: rutil-vm-wsproxy
    ports:
      - "9999:9999"
    environment:
      TZ: Asia/Seoul
      LANGUAGE: ko_KR;ko;en_US;en
      LC_ALL: ko_KR.UTF-8
      LANG: ko_KR.utf8
      PORT: 9999
    volumes:
      - /opt/rutilvm/rutil-vm/certs/fullchain.pem:/home/node/fullchain.pem:ro
    networks:
      - ovirt_network
    restart: unless-stopped

networks:
  ovirt_network:
    driver: bridge