version: "3"

services:
  rutil-vm-api:
    image: rutil-vm-api:latest
    container_name: rutil-vm-api
#    deploy:
#      mode: replicated
#      replicas: 2
    ports:
      - "6690:6690"
    environment:
      TZ: Asia/Seoul
      LANGUAGE: ko_KR;ko;en_US;en
      LC_ALL: ko_KR.UTF-8
      LANG: ko_KR.utf8
      RUTIL_VM_OVIRT_IP: 192.168.0.20
      RUTIL_VM_OVIRT_PORT_HTTPS: 8443
      RUTIL_VM_PORT_HTTPS: 6690
      RUTIL_VM_SSL_KEY_STORE: /app/certs/keystore.p12
      RUTIL_VM_SSL_KEY_STORE_PASSWORD: rutil-vm-api
      RUTIL_VM_SSL_KEY_ALIAS: rutil-vm-api
      RUTIL_VM_CORS_ALLOWED_ORIGINS: 192.168.0.20;localhost;rutil-vm;rutilvm-ititinfo.com
      RUTIL_VM_CORS_ALLOWED_ORIGINS_PORT: 3000;3443;443
      RUTIL_VM_OVIRT_LOGIN_LIMIT: 5
      RUTIL_VM_OVIRT_SSH_JSCH_LOG_ENABLED: true
      RUTIL_VM_OVIRT_SSH_JSCH_CONNECTION_TIMEOUT: 60000
      RUTIL_VM_OVIRT_SSH_CERT_LOCATION: /app/tmp
      RUTIL_VM_OVIRT_SSH_PRVKEY_LOCATION: /root/.ssh/id_rsa
      RUTIL_VM_OVIRT_SSH_ENGINE_ADDRESS: rutilvm@192.168.0.20:22
      RUTIL_VM_OVIRT_SSH_ENGINE_PRVKEY: |
        Bag Attributes
            localKeyID: 40 53 74 47 C9 2A 7A 28 A1 66 E9 3C E3 BD F1 2D F6 4F 43 B7 
        Key Attributes: <No Attributes>
        -----BEGIN PRIVATE KEY-----
        MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQDVIw1JN924PTqs
        ttc5K0wDrvoERiaajQ1tepJyQIpJrt7YJD4cI30BwDmMCxvsrJdqOfwQi3M+GM+7
        7vpQhb+C+8myufj2kfi1Ug2fslg6GPo+umsKADzSxAnqGnuFzkgKNOatUjU8Xuw2
        Ku1HY+743iVkYYuGmB7u2wu/20lylcblq1MvF6vdIXftIPIthL4ih1J3s4nShJBE
        8FEqx7wpqp18ylDAM6Hw7kwYc+52xLknY2oPU96NfTdCjq7oCyKjEaHE22ZLiE9l
        dpjIAkOXQllkkZTExBiQEh6l7hQFgSq5ZPWvjSPUq7/4Hj33WGNXhDvWyHbHwO9o
        fRDJ0jYhAgMBAAECggEBAI7Bw4xfFuroV/yHGvD3xxpQgLWMJx8tiujhSGWuRPHF
        Zw1ueQtv2bLqhaD/b9y+XUyROfv6612UUM+X6aE1dGjPLPHBDrhYXTVVmDp2whFn
        2XVad4djUVn6ZImg40tkN2xesoM0pOOi0KQXbIZ8sPuQD4uEqmekTFO/88a1oiRU
        ZLyHH7ZmljZ6GWAj2M5WHUH+3/u0MRzAkPu8DU6oGgKbOdCKtp0r27kG8RnJMXHh
        +CPhdNtXYVuzDaBs2oBcGNPf+d4RoDT1U9gvs6hpf91O/tmE0KO5awBEg2C/iEA1
        iKLJw1KlTdi6yr6YR3A6nbaDuMhy4OsEr21X7jiUq+ECgYEA7xvKxpWVQNG4Wcgg
        bAJqvW1IRRD3zdNeBbklKkjoCwzUHZo4f0eKk9JZb8bl5Qnf0npTiys4WaVJo2xq
        tP68RFY4kHT3VvAJ80tfV6YBC1cOmEkqRTRltHxGG48mEzkfIZ9BJGDqnzoH+4vF
        0I/bhqHuMly2OW+sOIqQnJLj7V8CgYEA5DGSAL19rdN39IO6uLr+gGdydJa3vZPV
        I+DdP4wiu3RVYJqNq7o+cQw68U81azKl232+Z8wx7uQR7lQMxXCeLRoU8KoaSLSe
        09XEI12luen9MISXQqMcwPWFKtsLghU5uFbTNR/txVO4IrTUrtv5oa7n7ANDr82H
        AbDboxnBDH8CgYEAo/yoloeyZFExIQo7CjiiIiZYAV5Axb3n5v7yuUxlMGbs9xx1
        EP3s0bLbOejsdKfQBJd2wqSysfDFTzqk+FsYnbmQc6p0lABuopiX3BHy92cOkGzl
        e68S7bSplG8ZyudLLZD+aUe6wddX8DINShvPkEdwiMPDCiNHt0N5KJkpjvsCgYEA
        1ZgQseCs4yguABHNlVxzHH24BKmPE0RtHUg90F27pPsfb207bqLGD8sC4RzjQ5QE
        646ny0C2/IU+w3ao/aaMaGshbqPKNoPapy5QiUn+9iavd9qkOxuyrmsiWxrtirWT
        cZjT2cYpKatTkCjzazk8ULsHG0Ny9/vJgyuoauKQcMECgYEAnh+ySmdNJ4DZApcW
        jbhv4NwoxsKsDTq+OiGpijUGe1yEUNYtkBHrpdxvtzVBBei74ea32CdDRc5vsuuy
        LXWanDNDUzumx7Vzl5iLay9cjtvNjc2q/zLzu0eSxhol8ZOKNWmogL0hVlFbIS6d
        8D1+bPLqZO65cF7pZPdxHkAlJOc=
        -----END PRIVATE KEY-----
      POSTGRES_JDBC_PORT: 5432
      POSTGRES_DATASOURCE_JDBC_ID: rutil
      POSTGRES_DATASOURCE_JDBC_PW: rutil1!
    volumes:
      - /opt/rutilvm/rutil-vm-api/logs:/app/logs:rw
      - /opt/rutilvm/rutil-vm-api/certs:/app/certs:rw
      - /opt/rutilvm/rutil-vm-api/tmp:/app/tmp:rw
      # - /root/.ssh:/root/.ssh:rw
      - /home/rutilvm/.ssh:/root/.ssh:rw
      - /etc/hosts:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ovirt_network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail https://localhost:6690/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  rutil-vm:
    image: rutil-vm:latest
    container_name: rutil-vm
    ports:
      - "443:443"
    environment:
      TZ: Asia/Seoul
      LANGUAGE: ko_KR;ko;en_US;en
      LC_ALL: ko_KR.UTF-8
      LANG: ko_KR.utf8
      NODE_ENV: production
      __RUTIL_VM_OVIRT_IP_ADDRESS__: 192.168.0.20
      __RUTIL_VM_LOGGING_ENABLED__: true
      __RUTIL_VM_ITEMS_PER_PAGE__: 25
      __RUTIL_VM_IS_LICENCE_VERIFIED__: false
      __RUTIL_VM_WATERMARK_TEXT__: 무단배포금지입니다
    volumes:
      - /opt/rutilvm/rutil-vm/certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/pki/ovirt-engine/keys:/etc/pki/ovirt-engine/keys:ro
    networks:
      - ovirt_network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail https://localhost:433 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    
  rutil-vm-wsproxy:
    image: rutil-vm-wsproxy:latest
    container_name: rutil-vm-wsproxy
    ports:
      - "9999:9999"
    environment:
      TZ: Asia/Seoul
      LANGUAGE: ko_KR;ko;en_US;en
      LC_ALL: ko_KR.UTF-8
      LANG: ko_KR.utf8
      PORT: 9999
    volumes:
      - /opt/rutilvm/rutil-vm/certs/fullchain.pem:/home/node/fullchain.pem:ro
    networks:
      - ovirt_network
    restart: unless-stopped

networks:
  ovirt_network:
    driver: bridge
