version: "3"

services:
  rutil-vm-api:
    image: ititcloud/rutil-vm-api:latest
    container_name: rutil-vm-api
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      TZ: Asia/Seoul
      LANGUAGE: ko_KR;ko;en_US;en
      LC_ALL: ko_KR.UTF-8
      LANG: ko_KR.utf8
      RUTIL_VM_OVIRT_IP: 192.168.0.20
      RUTIL_VM_OVIRT_PORT_HTTPS: 443
      RUTIL_VM_PORT_HTTPS: 8443
      RUTIL_VM_OVIRT_HOST_SSH_IP: 192.168.0.21
      RUTIL_VM_OVIRT_HOST_SSH_PORT: 22
      RUTIL_VM_OVIRT_HOST_SSH_ID: root
      RUTIL_VM_OVIRT_HOST_SSH_PW: adminRoot!@#
      RUTIL_VM_CORS_ALLOWED_ORIGINS: 192.168.0.70;localhost;rutil-vm
      RUTIL_VM_CORS_ALLOWED_ORIGINS_PORT: 3000;3443;443
      RUTIL_VM_OVIRT_SSH_JSCH_LOG_ENABLED: true
      RUTIL_VM_OVIRT_SSH_PRVKEY_LOCATION: /root/.ssh/id_rsa
      RUTIL_VM_OVIRT_SSH_ENGINE_ADDRESS: root@192.168.0.20:22
      RUTIL_VM_OVIRT_SSH_ENGINE_PRVKEY: |
        Bag Attributes
            localKeyID: E1 AC BA 03 48 4D 98 A2 76 E3 B4 B1 D8 06 A5 9F E8 57 1B BA 
        Key Attributes: <No Attributes>
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDjQYW0Apto4xAI
        6y1gSik0KMIPx3iU9XxvAuuR1MnlIy44KGypAQDfKlE6qSU1I7yBMzOmYVWooOfS
        yfb8mwcRIXZmXPi7hvhdu2j/Vv48EafLY0y53ipwLxdGcnFjmrSxX0rXOEQ1eAH8
        xUDugOxfyR7m6VwZ+tORVKWuy20GF+6uQuXpjlDKiX3J3rEQnCIhX12qUeh30PLR
        kDbs7YMZ4OiZs0+QdsJQlSUyVCSloF3ZC07Ljlx42XqsxIIdwsfEbQv2bduDh2vo
        /WQNeixde8Ma4dHAMG90d926fwxgMs5gAWKbQasTvCZDiQnjl2C4JfkBC6K+NdfH
        H+p2UfoBAgMBAAECggEAY60UgMz37zxQhyjnwSkmA2uxGoyqFePKjUJhopgLacZR
        em44orP+9uMvt6QC3tjq0Fxt1hcxJAJXS/wrqcYxhlEABovWySG9BBe0SPKWFjDE
        QRAv0gJg6M2uzsZZd4+em4GpaNaUDEOz03ONNE813hlvxWYrcHW0oDTZat5s1lOL
        Rb9hR0szHcZtcKzmiC/Rez6duLOu1ogYxwjSt07xjI9GqqNdq2KzKwc6qByKakNR
        yAPUn9ScNDNXosTDpDeSUrQ9coXwq4ovccwUuQoaJjUi0RZAMcd7GM3pt3xID+nP
        LGjdjdGr+04cRXcN84RtoAeDIFdCPJpIiWwAb7Yz9QKBgQD3D59cMM1y37NGXVJD
        DrTi4PegIjXVD35pZZYn3a7/+WV/ywcBvU2HFyZOuEgHp+5uCCCpCSeyvQ9CR6eG
        +lIj7Keng9evfgvT31ybj0yISwXJTAQGRURLlx/2+vGQuGwdW2xW7FnB22bN/mCN
        3HcRSd5Mu2qxBKEZmed2YJN7iwKBgQDrenUO0HctAsVfn9NfS0su34IaJCoCPCrk
        1vL2ilp6Xi8FgeCR6aLhhs3JT5B+pVnW2ZFTFsX9zpFN3bjiTNCdMlSCP7QqUO0J
        j6zIoBo3KL2ovp8V/tt14GFT/APLAVN5oVNdbuo/AsEy8L7CRb/E4va8GVzqdX2m
        DZ4bS7MCIwKBgQCwXq20AX7ZD8sKY1pzVo9ZG6KK5YEqjXn/wa6U3ROt1ptXxFdH
        LZ2n36XQMovxMzfpwtGV+lwlpAO9nCuDFzYGQU5aLquNs1y8LssMnhrTfUMvNZ31
        4ALmN4dxKCnE13MO7hIEZ4uX8YmNapgBDa7OX75bZru+jQB4pz7uafk/CwKBgBZl
        QibTitIcFlt+3uKMTa06kqwbzmcCA+5ZxyfNhsdml8BFVu9pshUS9hV0XMC+xymY
        7apiWxhFgipOsRvMxHZ+5+yvVFpF8hVbtcoq9/NRC6C16Hl2ELdITNlo+Y9gI+lI
        f54+Q0cU4v0OSoY9jfySvXasTtr5q6aUWvorm+3TAoGAHOsj9HQY30hsY/hIjgw5
        O4PZfe2WbM8W9aaMYb6+TMdmPfUbPx7vGg/woGFXsYJOHsLb6Zy391yGr7Yzh/Ax
        mPJcz2MN4bXHsWupUGwIuMtU/AU6E9yQf0LWakUjnDJkWNoL0ZgaNIoQgCNhRc8S
        jN7NiPAgvMHvnsKFzPbxRdU=
        -----END PRIVATE KEY-----
      RUTIL_VM_OVIRT_SSH_HOSTS_ADDRESS: root@192.168.0.21:22|root@192.168.0.22:22
      POSTGRES_JDBC_PORT: 5432
      POSTGRES_DATASOURCE_JDBC_ID: rutil
      POSTGRES_DATASOURCE_JDBC_PW: rutil1!
    volumes:
      - ./rutil-vm-api/logs:/app/logs:rw
      - /root/.ssh:/root/.ssh:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ovirt_network
#    healthcheck:
#      test: ["CMD-SHELL", "curl --silent --fail localhost:9600 || exit 1"]
#      interval: 10s
#      timeout: 10s
#      retries: 3
    restart: on-failure

  rutil-vm:
    image: ititcloud/rutil-vm:latest
    container_name: rutil-vm
    ports:
      - "3433:443"
    environment:
      - TZ=Asia/Seoul
      - LANGUAGE=ko_KR;ko;en_US;en
      - LC_ALL= ko_KR.UTF-8
      - LANG=ko_KR.utf8
    networks:
      - ovirt_network
#    healthcheck:
#      test: ["CMD-SHELL", "curl --silent --fail localhost:9600 || exit 1"]
#      interval: 10s
#      timeout: 10s
#      retries: 3
    restart: on-failure
    
#  nginx:
#    image: nginx:stable-alpine3.20-perl
#    platform: linux/amd64
#    container_name: nginx-proxy
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - rutil
#    networks:
#      - ovirt_network

networks:
  ovirt_network:
    driver: bridge